codecov:
  require_ci_to_pass: true
  branch: development
  max_report_age: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch: false
    project:
      default: false
      backend:
        target: 80%
        flags:
          - payapi
          - bcolapi
          - reportapi
          - paymentjobs
          - payqueue

ignore:
  - "^/tests/**/*" # ignore test harness code

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: true

flags:
  payapi:
    paths:
      - pay-api/src/pay_api
    carryforward: true
  bcolapi:
    paths:
      - bcol-api/src/bcol-api
    carryforward: true
  reportapi:
    paths:
      - report-api/src/api
    carryforward: true
  paymentjobs:
    paths:
      - jobs/payment-jobs/tasks
    carryforward: true
  payqueue:
      paths:
      - pay-queue/src/pay_queue
      carryforward: true

