version: "3.1"

services:
  ####################### AUTH Database Definition #######################
  paydb:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54332:5432"
    volumes:
      - db-data:/var/lib/postgresql/data2

  ####################### AUTH Unit Test Database Definition #######################
  paydb-test:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54333:5432"
    volumes:
      - db-data:/var/lib/postgresql/data3

  #################### Jaeger Tracing Service Definition ####################
  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    ports:
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"

volumes:
  db-data:
    driver: local
