kind: Template
apiVersion: v1
metadata:
  name: cron-update-stale-payment
  annotations:
    description: "Scheduled Task to cleanup update-stale-payment records"
    tags: cronjob
objects:
  - kind: CronJob
    apiVersion: batch/v1beta1
    metadata:
      name: cron-update-stale-payment
    spec:
      successfulJobsHistoryLimit: 5
      failedJobsHistoryLimit: 5
      schedule: "0 */4 * * *"
      suspend: false
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - name: update-stale-payment
                  image: "docker-registry.default.svc:5000/l4ygcl-tools/update-stale-payment:${ENV_TAG}"
                  imagePullPolicy: Always
                  args:
                    - /bin/sh
                    - "-c"
                    - "cd /opt/app-root/src; ./run.sh"
                  env:
                    - name: DATABASE_USERNAME
                      valueFrom:
                        secretKeyRef:
                          key: DATABASE_USERNAME
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: DATABASE_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: DATABASE_PASSWORD
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: DATABASE_NAME
                      valueFrom:
                        secretKeyRef:
                          key: DATABASE_NAME
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: DATABASE_HOST
                      valueFrom:
                        secretKeyRef:
                          key: DATABASE_HOST
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: DATABASE_PORT
                      valueFrom:
                        secretKeyRef:
                          key: DATABASE_PORT
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: JWT_OIDC_JWKS_CACHE_TIMEOUT
                      valueFrom:
                        secretKeyRef:
                          key: JWT_OIDC_JWKS_CACHE_TIMEOUT
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: KEYCLOAK_BASE_URL
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_BASE_URL
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: NATS_SUBJECT
                      valueFrom:
                        secretKeyRef:
                          key: NATS_SUBJECT
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: REPORT_API_BASE_URL
                      valueFrom:
                        secretKeyRef:
                          key: REPORT_API_BASE_URL
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: SENTRY_DSN
                      valueFrom:
                        secretKeyRef:
                          key: SENTRY_DSN
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: BCOL_FEE_CODE
                      valueFrom:
                        secretKeyRef:
                          key: BCOL_FEE_CODE
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: BCOL_LDAP_USER_DN_PATTERN
                      valueFrom:
                        secretKeyRef:
                          key: BCOL_LDAP_USER_DN_PATTERN
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: KEYCLOAK_REALMNAME
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_REALMNAME
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: PAYBC_CONNECT_TIMEOUT
                      valueFrom:
                        secretKeyRef:
                          key: PAYBC_CONNECT_TIMEOUT
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: AUTH_API_ENDPOINT
                      valueFrom:
                        secretKeyRef:
                          key: AUTH_API_ENDPOINT
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: DATABASE_ADMIN_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: DATABASE_ADMIN_PASSWORD
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: NATS_CLUSTER_ID
                      valueFrom:
                        secretKeyRef:
                          key: NATS_CLUSTER_ID
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: BCOL_LINK_CODE
                      valueFrom:
                        secretKeyRef:
                          key: BCOL_LINK_CODE
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: BCOL_LDAP_SERVER
                      valueFrom:
                        secretKeyRef:
                          key: BCOL_LDAP_SERVER
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: BCOL_QUERY_PROFILE_WSDL_URL
                      valueFrom:
                        secretKeyRef:
                          key: BCOL_QUERY_PROFILE_WSDL_URL
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: JWT_OIDC_AUDIENCE
                      valueFrom:
                        secretKeyRef:
                          key: JWT_OIDC_AUDIENCE
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: KEYCLOAK_AUTH_AUDIENCE
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_AUTH_AUDIENCE
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: PAYBC_CLIENT_ID
                      valueFrom:
                        secretKeyRef:
                          key: PAYBC_CLIENT_ID
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: AUTH_WEB_PAY_TRANSACTION_URL
                      valueFrom:
                        secretKeyRef:
                          key: AUTH_WEB_PAY_TRANSACTION_URL
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: KEYCLOAK_ADMIN_SECRET
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_ADMIN_SECRET
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: KEYCLOAK_AUTH_CLIENT_SECRET
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_AUTH_CLIENT_SECRET
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: NATS_SERVERS
                      valueFrom:
                        secretKeyRef:
                          key: NATS_SERVERS
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: PAYBC_BASE_URL
                      valueFrom:
                        secretKeyRef:
                          key: PAYBC_BASE_URL
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: PAYBC_GENERATE_RANDOM_INVOICE_NUMBER
                      valueFrom:
                        secretKeyRef:
                          key: PAYBC_GENERATE_RANDOM_INVOICE_NUMBER
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: BCOL_PAYMENTS_WSDL_URL
                      valueFrom:
                        secretKeyRef:
                          key: BCOL_PAYMENTS_WSDL_URL
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: DATABASE_USER
                      valueFrom:
                        secretKeyRef:
                          key: DATABASE_USER
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: JWT_OIDC_CLIENT_SECRET
                      valueFrom:
                        secretKeyRef:
                          key: JWT_OIDC_CLIENT_SECRET
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: NATS_CLIENT_NAME
                      valueFrom:
                        secretKeyRef:
                          key: NATS_CLIENT_NAME
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: VALID_REDIRECT_URLS
                      valueFrom:
                        secretKeyRef:
                          key: VALID_REDIRECT_URLS
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: BCOL_DEBIT_ACCOUNT_VERSION
                      valueFrom:
                        secretKeyRef:
                          key: BCOL_DEBIT_ACCOUNT_VERSION
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: JWT_OIDC_ALGORITHMS
                      valueFrom:
                        secretKeyRef:
                          key: JWT_OIDC_ALGORITHMS
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: JWT_OIDC_WELL_KNOWN_CONFIG
                      valueFrom:
                        secretKeyRef:
                          key: JWT_OIDC_WELL_KNOWN_CONFIG
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: KEYCLOAK_ADMIN_CLIENTID
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_ADMIN_CLIENTID
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: PAYBC_CLIENT_SECRET
                      valueFrom:
                        secretKeyRef:
                          key: PAYBC_CLIENT_SECRET
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: PAYBC_PORTAL_URL
                      valueFrom:
                        secretKeyRef:
                          key: PAYBC_PORTAL_URL
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: NATS_QUEUE
                      valueFrom:
                        secretKeyRef:
                          key: NATS_QUEUE
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: JWT_OIDC_ISSUER
                      valueFrom:
                        secretKeyRef:
                          key: JWT_OIDC_ISSUER
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: PAYBC_MEMO_LINE_NAME
                      valueFrom:
                        secretKeyRef:
                          key: PAYBC_MEMO_LINE_NAME
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: BCOL_API_ENDPOINT
                      valueFrom:
                        secretKeyRef:
                          key: BCOL_API_ENDPOINT
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: KEYCLOAK_SERVICE_ACCOUNT_ID
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_SERVICE_ACCOUNT_ID
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: KEYCLOAK_SERVICE_ACCOUNT_SECRET
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_SERVICE_ACCOUNT_SECRET
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: KEYCLOAK_BCROS_ADMIN_SECRET
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_BCROS_ADMIN_SECRET
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: KEYCLOAK_BCROS_REALMNAME
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_BCROS_REALMNAME
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: KEYCLOAK_BCROS_ADMIN_CLIENTID
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_BCROS_ADMIN_CLIENTID
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: KEYCLOAK_BCROS_BASE_URL
                      valueFrom:
                        secretKeyRef:
                          key: KEYCLOAK_BCROS_BASE_URL
                          name: "pay-api-${TAG_NAME}-secret"
                    - name: JWT_OIDC_CACHING_ENABLED
                      valueFrom:
                        secretKeyRef:
                          key: JWT_OIDC_CACHING_ENABLED
                          name: "pay-api-${TAG_NAME}-secret"

              restartPolicy: Never
              concurrencyPolicy: Forbid
parameters:
  - name: ENV_TAG
    displayName: ENV_TAG
    description: "The name assigned to all of the OpenShift resources associated to the\nserver instance."
    required: true
    value: latest
  - name: NAME
    displayName: Name
    description: "The name assigned to all of the OpenShift resources associated to the\nserver instance."
    required: true
    value: pay-api
  - name: APP_GROUP
    displayName: "App Group"
    description: "The name assigned to all of the deployments in this project."
    required: true
    value: sbc-pay
  - name: IMAGE_NAMESPACE
    displayName: "Image Namespace"
    required: true
    description: "The namespace of the OpenShift project containing the imagestream for\nthe application."
    value: l4ygcl-tools
  - name: TAG_NAME
    displayName: "Environment TAG name"
    description: "The TAG name for this environment, e.g., dev, test, prod"
    required: true
    value: dev
  - name: DATABASE_NAME
    displayName: "Database App Name"
    description: "A valid database app name used by the service."
    required: true
    value: postgresql
  - name: CPU_REQUEST
    displayName: "Resources CPU Request"
    description: "The resources CPU request (in cores) for this build."
    required: true
    value: 100m
  - name: CPU_LIMIT
    displayName: "Resources CPU Limit"
    description: "The resources CPU limit (in cores) for this build."
    required: true
    value: 750m
  - name: MEMORY_REQUEST
    displayName: "Resources Memory Request"
    description: "The resources Memory request (in Mi, Gi, etc) for this build."
    required: true
    value: 100Mi
  - name: MEMORY_LIMIT
    displayName: "Resources Memory Limit"
    description: "The resources Memory limit (in Mi, Gi, etc) for this build."
    required: true
    value: 2Gi
  - name: REPLICAS
    displayName: "The number of replicas to run"
    description: "The number of replicas to run in this environment."
    required: true
    value: "1"
  - name: JAEGER_COLLECTOR
    displayName: "Jaeger Tracing collector address"
    description: "Jaeger Tracing collector address."
    required: true
    value: "--collector.host-port=jaeger-collector.d7eovc-dev.svc:14267"
