openapi: 3.0.0
info:
  title: report-api.yaml
  version: '1.1'
  description: Report API
paths:
  /reports:
    post:
      summary: Create pdf report.
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              description: Content encoding of the response. This header is optional and may not be present.
              schema:
                type: string
                enum:
                  - gzip
                  - identity
          content:
            application/json:
              schema:
                type: object
              examples:
                example1:
                  value:
                    test: test
            # text/csv:
            #   schema:
            #     type: object
            #   examples:
            #     example1:
            #       value:
            #         test: test
      description: Create pdf report.
      operationId: post_report
      parameters:
        - name: Content-Encoding
          in: header
          description: Content encoding of the request body. Supports gzip encoding.
          required: false
          schema:
            type: string
            enum:
              - gzip
              - identity
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: object
              properties:
                reportName:
                  type: string
                templateVars:
                  type: object
                populatePageNumber:
                  type: boolean
                templateName:
                  type: string
                template:
                  type: string
            examples: {}
        required: false
components:
  schemas: {}

