openapi: 3.0.0
info:
  title: report-api.yaml
  version: '1.1'
  description: Report API

paths:
  /reports:
    post:
      summary: Create pdf report.
      description: Create pdf report.
      operationId: post_report

      parameters:
        - name: Content-Encoding
          in: header
          description: Content encoding of the request body.
          required: false
          schema:
            type: string
            enum: [gzip, identity]

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object

          application/gzip:
            schema:
              type: string
              format: binary

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  test:
                    type: string
