openapi: 3.0.0
info:
  title: test
  version: "1.0"

paths:
  /reports:
    post:
      summary: test
      requestBody:
        required: false
        content:
          application/gzip:
            schema:
              type: string
              format: binary
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
