"""bcorp_filing_types

Revision ID: 110be55ccb82
Revises: 1a4e08683cb2
Create Date: 2019-12-16 09:08:29.440422

"""
from datetime import datetime, timezone

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Date, Float, Integer, String
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = '00467a306afd'
down_revision = '1a4e08683cb2'
branch_labels = None
depends_on = None


def upgrade():
 	# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_schedule', sa.Column('future_effective_fee_code', sa.String(length=10), nullable=True))
    op.add_column('fee_schedule', sa.Column('priority_fee_code', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'fee_schedule', 'fee_code', ['priority_fee_code'], ['code'])
    op.create_foreign_key(None, 'fee_schedule', 'fee_code', ['future_effective_fee_code'], ['code'])
    # ### end Alembic commands ###

    # Delete existing BCORP fee codes
    # op.execute('DELETE FROM fee_schedule where corp_type_code=\'BC\'')

    op.execute("update corp_type set description='BC Company' where code='BC'")

    fee_code_table = table("fee_code", column("code", String), column("amount", Float))
    
    filing_type_table = table(
        "filing_type", column("code", String), column("description", String)
    )
    
    fee_schedule_table = table(
        "fee_schedule",
        column("filing_type_code", String),
        column("corp_type_code", String),
        column("fee_code", String),
        column("fee_start_date", Date),
        column("fee_end_date", Date),
        column("future_effective_fee_code", String),
        column("priority_fee_code", String)
    )

    # Fee Codes
    op.bulk_insert(
        fee_code_table, [
            {"code": "EN109", "amount": 350},
            {"code": "FUT01", "amount": 100},
            {"code": "PRI01", "amount": 100}
        ]
    )

    # Filing Types
    op.bulk_insert(
        filing_type_table,
        [
            {'code': 'BCANN', 'description': 'Annual Report'},
            {'code': 'BCADD', 'description': 'Change of Registered Office Address'},
            {'code': 'BCCDR', 'description': 'Change of Director'},
            {'code': 'BCINC', 'description': 'Incorporation'},
            {'code': 'BCCGM', 'description': 'Notice of Change'},
            {'code': 'BCFDR', 'description': 'Change of Director'},
            {'code': 'BCAMR', 'description': 'Amalgamation Application (Regular)'},
            {'code': 'BCAMH', 'description': 'Amalgamation Application Short Form (Horizontal)'},
            {'code': 'BCAMV', 'description': 'Amalgamtion Application Short Form (Vertical)'},
            {'code': 'BCRSF', 'description': 'Restoration Application - Full for a BC Benefit Company'},
            {'code': 'BCRSL', 'description': 'Restoration Application - Limited for a BC Benefit Company'},
            {'code': 'BCRSC', 'description': 'Restoration Application (Convert Limited to Full) for a BC Benefit Company'},
            {'code': 'BCRSX', 'description': 'Restoration Application (Extend time Limit) for a BC Benefit Company'},
            {'code': 'BCREG', 'description': 'Registration'}

       ]
    )


    op.bulk_insert(
        fee_schedule_table,
        [
            {
                "filing_type_code": "BCANN",
                "corp_type_code": "BC",
                "fee_code": "EN108",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": None,
            },
            {
                "filing_type_code": "BCADD",
                "corp_type_code": "BC",
                "fee_code": "EN101",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": None,
            },
            {
                "filing_type_code": "BCCDR",
                "corp_type_code": "BC",
                "fee_code": "EN101",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": None,
            },
            {
                "filing_type_code": "BCINC",
                "corp_type_code": "BC",
                "fee_code": "EN109",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": "FUT01",
                "priority_fee_code": None,
            },
            {
                "filing_type_code": "BCREG",
                "corp_type_code": "BC",
                "fee_code": "EN109",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": None,
            },
            {
                "filing_type_code": "BCCGM",
                "corp_type_code": "BC",
                "fee_code": "EN107",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": None,
            },
            {
                "filing_type_code": "BCRSC",
                "corp_type_code": "BC",
                "fee_code": "EN101",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": "PRI01",
            },
            {
                "filing_type_code": "BCFDR",
                "corp_type_code": "BC",
                "fee_code": "EN107",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": None,
            },
            {
                "filing_type_code": "BCAMR",
                "corp_type_code": "BC",
                "fee_code": "EN109",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": "FUT01",
                "priority_fee_code": "PRI01",
            },
            {
                "filing_type_code": "BCAMH",
                "corp_type_code": "BC",
                "fee_code": "EN109",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": "FUT01",
                "priority_fee_code": "PRI01",
            },
            {
                "filing_type_code": "BCAMV",
                "corp_type_code": "BC",
                "fee_code": "EN109",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": "FUT01",
                "priority_fee_code": "PRI01",
            },
            {
                "filing_type_code": "BCRSF",
                "corp_type_code": "BC",
                "fee_code": "EN109",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": "PRI01",
            },
            {
                "filing_type_code": "BCRSL",
                "corp_type_code": "BC",
                "fee_code": "EN109",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": "PRI01",
            },
            {
                "filing_type_code": "BCRSX",
                "corp_type_code": "BC",
                "fee_code": "EN109",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": "PRI01",
            }
        ],
    )


def downgrade():
    #Delete fee related master data
    op.execute('DELETE FROM fee_schedule where corp_type_code=\'BC\'')
    op.execute("DELETE FROM filing_type where code in ('BCANN','BCADD','BCCDR', 'BCINC', 'BCCGM', 'BCFDR', 'BCAMR', 'BCAMH', 'BCAMV', 'BCRSF', 'BCRSL', 'BCRSC', 'BCRSX', 'BCREG')")
    op.execute("DELETE FROM fee_code where code in ('EN109','FUT01','PRI01')")
    # ###Delete End

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_schedule', 'priority_fee_code')
    op.drop_column('fee_schedule', 'future_effective_fee_code')
    # ### end Alembic commands ###

    
