"""Remove audit columns for distribution_code_links.

Revision ID: 0251b328a0d9
Revises: e06565b323db
Create Date: 2022-07-19 20:31:28.417877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0251b328a0d9'
down_revision = 'e06565b323db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distribution_code_links', 'updated_name')
    op.drop_column('distribution_code_links', 'created_name')
    op.drop_column('distribution_code_links', 'created_by')
    op.drop_column('distribution_code_links', 'updated_by')
    op.drop_column('distribution_code_links', 'updated_on')
    op.drop_column('distribution_code_links', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_code_links', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('distribution_code_links', sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('distribution_code_links', sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('distribution_code_links', sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('distribution_code_links', sa.Column('created_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('distribution_code_links', sa.Column('updated_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
