"""empty message

Revision ID: 0449261c3fa7
Revises: e699674b1774
Create Date: 2020-12-07 10:26:11.049160

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0449261c3fa7"
down_revision = "e699674b1774"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment", sa.Column("created_by", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "payment", sa.Column("receipt_number", sa.String(length=50), nullable=True)
    )
    op.create_index(
        op.f("ix_payment_receipt_number"), "payment", ["receipt_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_receipt_number"), table_name="payment")
    op.drop_column("payment", "receipt_number")
    op.drop_column("payment", "created_by")
    # ### end Alembic commands ###
