"""jv_feedback_changes

Revision ID: 073b9f59b447
Revises: 1803b51e5689
Create Date: 2021-02-23 09:02:09.797138

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "073b9f59b447"
down_revision = "1803b51e5689"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "distribution_codes", sa.Column("stop_ejv", sa.Boolean(), nullable=True)
    )
    op.add_column("ejv_files", sa.Column("message", sa.String(), nullable=True))
    op.add_column("ejv_headers", sa.Column("message", sa.String(), nullable=True))
    op.add_column(
        "ejv_invoice_links",
        sa.Column("disbursement_status_code", sa.String(length=20), nullable=True),
    )
    op.add_column("ejv_invoice_links", sa.Column("message", sa.String(), nullable=True))
    op.create_foreign_key(
        "ejv_invoice_link_disbursement_status_code_fk",
        "ejv_invoice_links",
        "disbursement_status_codes",
        ["disbursement_status_code"],
        ["code"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ejv_invoice_link_disbursement_status_code_fk",
        "ejv_invoice_links",
        type_="foreignkey",
    )
    op.drop_column("ejv_invoice_links", "message")
    op.drop_column("ejv_invoice_links", "disbursement_status_code")
    op.drop_column("ejv_headers", "message")
    op.drop_column("ejv_files", "message")
    op.drop_column("distribution_codes", "stop_ejv")

    # ### end Alembic commands ###
