"""notification tables added

Revision ID: 07f7475c9552
Revises: 71c733c91cbf
Create Date: 2020-08-25 12:15:01.102297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f7475c9552'
down_revision = '71c733c91cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_status_code',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('account_notification_preference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_account_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['payment_account_id'], ['payment_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_notification_preference_payment_account_id'), 'account_notification_preference', ['payment_account_id'], unique=False)
    op.create_table('notification_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('payment_account_id', sa.Integer(), nullable=True),
    sa.Column('notification_preference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_preference_id'], ['account_notification_preference.id'], ),
    sa.ForeignKeyConstraint(['payment_account_id'], ['payment_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_recipients_auth_user_id'), 'notification_recipients', ['auth_user_id'], unique=False)
    op.create_index(op.f('ix_notification_recipients_notification_preference_id'), 'notification_recipients', ['notification_preference_id'], unique=False)
    op.create_index(op.f('ix_notification_recipients_payment_account_id'), 'notification_recipients', ['payment_account_id'], unique=False)
    op.add_column('payment_account', sa.Column('auth_account_name', sa.String(length=250), nullable=True))
    op.create_index(op.f('ix_payment_account_auth_account_name'), 'payment_account', ['auth_account_name'], unique=False)
    op.add_column('statement', sa.Column('notification_date', sa.Date(), nullable=True))
    op.add_column('statement', sa.Column('notification_status_code', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'statement', 'notification_status_code', ['notification_status_code'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statement', type_='foreignkey')
    op.drop_column('statement', 'notification_status_code')
    op.drop_column('statement', 'notification_date')
    op.drop_index(op.f('ix_payment_account_auth_account_name'), table_name='payment_account')
    op.drop_column('payment_account', 'auth_account_name')
    op.drop_index(op.f('ix_notification_recipients_payment_account_id'), table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_notification_preference_id'), table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_auth_user_id'), table_name='notification_recipients')
    op.drop_table('notification_recipients')
    op.drop_index(op.f('ix_account_notification_preference_payment_account_id'), table_name='account_notification_preference')
    op.drop_table('account_notification_preference')
    op.drop_table('notification_status_code')
    # ### end Alembic commands ###
