"""routing_slip_refund_amount

Revision ID: 0d885750ded9
Revises: aa9207187d6b
Create Date: 2021-12-14 10:19:33.738170

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0d885750ded9"
down_revision = "aa9207187d6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routing_slips", sa.Column("refund_amount", sa.Numeric(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routing_slips", "refund_amount")
    # ### end Alembic commands ###
