"""parent routing slip number

Revision ID: 10fa4c64f1da
Revises: c12b11093a87
Create Date: 2021-08-16 13:37:27.441684

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "10fa4c64f1da"
down_revision = "c12b11093a87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routing_slips", sa.Column("parent_number", sa.String(), nullable=True)
    )
    op.drop_constraint(
        "routing_slips_parent_id_fkey", "routing_slips", type_="foreignkey"
    )
    op.create_foreign_key(
        "routing_slips_parent_id_fkey",
        "routing_slips",
        "routing_slips",
        ["parent_number"],
        ["number"],
    )
    op.drop_column("routing_slips", "parent_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routing_slips",
        sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "routing_slips_parent_id_fkey", "routing_slips", type_="foreignkey"
    )
    op.create_foreign_key(
        "routing_slips_parent_id_fkey",
        "routing_slips",
        "routing_slips",
        ["parent_id"],
        ["id"],
    )
    op.drop_column("routing_slips", "parent_number")
    # ### end Alembic commands ###
