"""Use numeric instead of float for payment account credit. 

Revision ID: 160d44b02e09
Revises: 7fddd6ffe782
Create Date: 2022-11-02 08:38:35.088479

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "160d44b02e09"
down_revision = "7fddd6ffe782"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payment_accounts",
        "credit",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_accounts_version",
        "credit",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=True,
        autoincrement=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payment_accounts_version",
        "credit",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
        autoincrement=False,
    )
    op.alter_column(
        "payment_accounts",
        "credit",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
