"""premium_flow_initial_changes

Revision ID: 1a4e08683cb2
Revises: a22d758c6670
Create Date: 2019-11-25 10:54:24.037481

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import String
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = "1a4e08683cb2"
down_revision = "a22d758c6670"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice", sa.Column("folio_number", sa.String(length=50), nullable=True)
    )
    op.create_index(
        op.f("ix_invoice_folio_number"), "invoice", ["folio_number"], unique=False
    )
    op.add_column(
        "payment_account", sa.Column("user_id", sa.String(length=50), nullable=True)
    )
    op.create_index(
        op.f("ix_payment_account_account_number"),
        "payment_account",
        ["account_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_account_user_id"), "payment_account", ["user_id"], unique=False
    )

    payment_system_table = table(
        "payment_system", column("code", String), column("description", String)
    )
    payment_method_table = table(
        "payment_method", column("code", String), column("description", String)
    )

    op.bulk_insert(
        payment_method_table, [{"code": "PREMIUM", "description": "Premium Payment"}]
    )

    op.bulk_insert(
        payment_system_table, [{"code": "BCOL", "description": "BC Online System"}]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_account_user_id"), table_name="payment_account")
    op.drop_index(
        op.f("ix_payment_account_account_number"), table_name="payment_account"
    )
    op.drop_column("payment_account", "user_id")
    op.drop_index(op.f("ix_invoice_folio_number"), table_name="invoice")
    op.drop_column("invoice", "folio_number")
    # ### end Alembic commands ###
