"""empty message

Revision ID: 1e62e1c27b08
Revises: 160d44b02e09
Create Date: 2022-11-07 15:19:29.515671

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1e62e1c27b08"
down_revision = "160d44b02e09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fee_codes",
        "amount",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "fee_codes",
        "amount",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
