"""empty message

Revision ID: e296910623cd
Revises: 286acad5d366
Create Date: 2023-02-07 12:17:04.806485

"""

from alembic import op
import sqlalchemy as sa
from time import sleep


# revision identifiers, used by Alembic.
revision = "e296910623cd"
down_revision = "286acad5d366"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("set statement_timeout=20000;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_invoice_references_invoice_id"),
        "invoice_references",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_references_status_code"),
        "invoice_references",
        ["status_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    op.execute("set statement_timeout=20000;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_invoice_references_status_code"), table_name="invoice_references"
    )
    op.drop_index(
        op.f("ix_invoice_references_invoice_id"), table_name="invoice_references"
    )
    # ### end Alembic commands ###
