"""Add overdue date to invoices.

Revision ID: 3a21a14b4137
Revises: 33bbd4d9a85c
Create Date: 2023-09-25 13:20:03.578472

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a21a14b4137"
down_revision = "33bbd4d9a85c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("overdue_date", sa.DateTime(), nullable=True))
    op.execute(
        "insert into invoice_status_codes (code, description) values ('OVERDUE', 'Overdue')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "overdue_date")
    op.execute("delete from invoice_status_codes where code = 'OVERDUE'")
    # ### end Alembic commands ###
