"""EFT Short names add audit fields for linking

Revision ID: bbd1189e4e75
Revises: 4f87e62bc81e
Create Date: 2024-02-02 09:41:11.363804

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bbd1189e4e75"
down_revision = "4f87e62bc81e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "eft_short_names", sa.Column("linked_by", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "eft_short_names",
        sa.Column("linked_by_name", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "eft_short_names", sa.Column("linked_on", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "eft_short_names_version",
        sa.Column(
            "linked_by", sa.String(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "eft_short_names_version",
        sa.Column(
            "linked_by_name", sa.String(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "eft_short_names_version",
        sa.Column("linked_on", sa.DateTime(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("eft_short_names_version", "linked_on")
    op.drop_column("eft_short_names_version", "linked_by_name")
    op.drop_column("eft_short_names_version", "linked_by")
    op.drop_column("eft_short_names", "linked_on")
    op.drop_column("eft_short_names", "linked_by_name")
    op.drop_column("eft_short_names", "linked_by")
    # ### end Alembic commands ###
