"""Fix audit columns for eft_refunds.

Revision ID: 75a39e02c746
Revises: 29f59e6f147b
Create Date: 2024-09-20 13:45:35.132557

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
# Note you may see foreign keys with distribution_codes_history
# For disbursement_distribution_code_id, service_fee_distribution_code_id
# Please ignore those lines and don't include in migration.

revision = "75a39e02c746"
down_revision = "29f59e6f147b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("eft_refunds", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("created_name", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("updated_name", sa.String(length=50), nullable=True)
        )
        batch_op.alter_column(
            "updated_by",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=50),
            existing_nullable=True,
        )
        batch_op.drop_column("updated_by_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("eft_refunds", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_by_name",
                sa.VARCHAR(length=100),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.alter_column(
            "updated_by",
            existing_type=sa.String(length=50),
            type_=sa.VARCHAR(length=100),
            existing_nullable=True,
        )
        batch_op.drop_column("updated_name")
        batch_op.drop_column("created_name")
    # ### end Alembic commands ###
