"""Add in a table that tracks credits from the CSV 

Revision ID: 33217f9c7af9
Revises: 56c4542db0d7
Create Date: 2024-10-04 12:46:18.633059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# Note you may see foreign keys with distribution_codes_history
# For disbursement_distribution_code_id, service_fee_distribution_code_id
# Please ignore those lines and don't include in migration.

revision = '33217f9c7af9'
down_revision = '56c4542db0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfs_credit_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('amount_applied', sa.Numeric(), nullable=False),
    sa.Column('cfs_account', sa.String(length=50), nullable=False),
    sa.Column('cfs_identifier', sa.String(length=50), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('invoice_amount', sa.Numeric(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['payment_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cfs_credit_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfs_credit_invoices_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cfs_credit_invoices_cfs_account'), ['cfs_account'], unique=False)
        batch_op.create_index(batch_op.f('ix_cfs_credit_invoices_cfs_identifier'), ['cfs_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfs_credit_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfs_credit_invoices_cfs_identifier'))
        batch_op.drop_index(batch_op.f('ix_cfs_credit_invoices_cfs_account'))
        batch_op.drop_index(batch_op.f('ix_cfs_credit_invoices_account_id'))

    op.drop_table('credit_invoices')
    # ### end Alembic commands ###
