""" EFT GL Transfer tracking

Revision ID: ff245db0cf76
Revises: eec11500a81e
Create Date: 2024-01-08 08:57:56.456585

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ff245db0cf76"
down_revision = "eec11500a81e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # EFT gl transfer tracking table
    op.create_table(
        "eft_gl_transfers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("transfer_date", sa.DateTime(), nullable=False),
        sa.Column("transfer_type", sa.String(length=50), nullable=False),
        sa.Column("transfer_amount", sa.Numeric(precision=19, scale=2), nullable=False),
        sa.Column("source_gl", sa.String(length=50), nullable=False),
        sa.Column("target_gl", sa.String(length=50), nullable=False),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column("processed_on", sa.DateTime(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=True),
        sa.Column("short_name_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["short_name_id"],
            ["eft_short_names.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eft_gl_transfers_transfer_date"),
        "eft_gl_transfers",
        ["transfer_date"],
        unique=False,
    )

    # Add credit to invoice link to track what invoice are eft funds applied to
    op.create_table(
        "eft_credit_invoice_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("eft_credit_id", sa.Integer(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["eft_credit_id"],
            ["eft_credits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eft_credit_invoice_links_eft_credit_id"),
        "eft_credit_invoice_links",
        ["eft_credit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eft_credit_invoice_links_invoice_id"),
        "eft_credit_invoice_links",
        ["invoice_id"],
        unique=False,
    )

    # Add link between credits and the eft_transaction from TDI17 it came from for easier auditing
    op.add_column(
        "eft_credits", sa.Column("eft_transaction_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "eft_credits", "eft_transactions", ["eft_transaction_id"], ["id"]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_eft_gl_transfers_transfer_date"), table_name="eft_gl_transfers"
    )
    op.drop_table("eft_gl_transfers")
    op.drop_index(
        op.f("ix_eft_credit_invoice_links_invoice_id"),
        table_name="eft_credit_invoice_links",
    )
    op.drop_index(
        op.f("ix_eft_credit_invoice_links_eft_credit_id"),
        table_name="eft_credit_invoice_links",
    )
    op.drop_table("eft_credit_invoice_links")
    op.drop_column("eft_credits", "eft_transaction_id")
    # ### end Alembic commands ###
