"""Migration that should clean up the history a bit.

Revision ID: 20c6b4b99be4
Revises: f9c15c7f29f5
Create Date: 2024-07-25 15:19:10.718113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c6b4b99be4'
down_revision = 'f9c15c7f29f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribution_codes_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'distribution_codes_history', ['disbursement_distribution_code_id'], ['distribution_code_id'])
        batch_op.create_foreign_key(None, 'distribution_codes_history', ['service_fee_distribution_code_id'], ['distribution_code_id'])

    with op.batch_alter_table('eft_credit_invoice_links', schema=None) as batch_op:
        batch_op.alter_column('status_code',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)

    with op.batch_alter_table('eft_refunds', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('ejv_links', schema=None) as batch_op:
        batch_op.alter_column('link_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index('ix_ejv_invoice_links_ejv_header_id')
        batch_op.drop_index('ix_ejv_links_link_type_link_id')
        batch_op.create_index(batch_op.f('ix_ejv_links_ejv_header_id'), ['ejv_header_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ejv_links_link_id'), ['link_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ejv_links_link_type'), ['link_type'], unique=False)

    with op.batch_alter_table('refunds_partial', schema=None) as batch_op:
        batch_op.alter_column('disbursement_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refunds_partial', schema=None) as batch_op:
        batch_op.alter_column('disbursement_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('ejv_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ejv_links_link_type'))
        batch_op.drop_index(batch_op.f('ix_ejv_links_link_id'))
        batch_op.drop_index(batch_op.f('ix_ejv_links_ejv_header_id'))
        batch_op.create_index('ix_ejv_links_link_type_link_id', ['link_type', 'link_id'], unique=False)
        batch_op.create_index('ix_ejv_invoice_links_ejv_header_id', ['ejv_header_id'], unique=False)
        batch_op.alter_column('link_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('eft_refunds', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('eft_credit_invoice_links', schema=None) as batch_op:
        batch_op.alter_column('status_code',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)

    with op.batch_alter_table('distribution_codes_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
