"""Update eft_transactions table to track dates from TDI17

Revision ID: a9bf3eaeda7b
Revises: 81c6a133a84a
Create Date: 2024-01-25 13:42:55.428494

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9bf3eaeda7b"
down_revision = "81c6a133a84a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "eft_transactions", sa.Column("deposit_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "eft_transactions", sa.Column("transaction_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("eft_transactions", "transaction_date")
    op.drop_column("eft_transactions", "deposit_date")
    # ### end Alembic commands ###
