"""19762 - Tables for Partial refunds.

Revision ID: 1ec047cf4308
Revises: bbd1189e4e75
Create Date: 2024-02-14 13:49:03.140504

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1ec047cf4308"
down_revision = "bbd1189e4e75"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Refunds Partial Versioning
    op.create_table(
        "refunds_partial_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "payment_line_item_id", sa.Integer(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "refund_type", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "refund_amount",
            sa.Numeric(precision=19, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_on", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_on", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "created_by", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_name", sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_by", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_name", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_refunds_partial_version_end_transaction_id"),
        "refunds_partial_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refunds_partial_version_operation_type"),
        "refunds_partial_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refunds_partial_version_payment_line_item_id"),
        "refunds_partial_version",
        ["payment_line_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refunds_partial_version_transaction_id"),
        "refunds_partial_version",
        ["transaction_id"],
        unique=False,
    )

    # Refunds Partial Table
    op.create_table(
        "refunds_partial",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("payment_line_item_id", sa.Integer(), nullable=False),
        sa.Column("refund_type", sa.String(length=50), nullable=True),
        sa.Column("refund_amount", sa.Numeric(precision=19, scale=2), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.String(length=50), nullable=False),
        sa.Column("created_name", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=50), nullable=True),
        sa.Column("updated_name", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_line_item_id"],
            ["payment_line_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refunds_partial_payment_line_item_id"),
        "refunds_partial",
        ["payment_line_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_refunds_partial_payment_line_item_id"), table_name="refunds_partial"
    )
    op.drop_table("refunds_partial")
    op.drop_index(
        op.f("ix_refunds_partial_version_transaction_id"),
        table_name="refunds_partial_version",
    )
    op.drop_index(
        op.f("ix_refunds_partial_version_payment_line_item_id"),
        table_name="refunds_partial_version",
    )
    op.drop_index(
        op.f("ix_refunds_partial_version_operation_type"),
        table_name="refunds_partial_version",
    )
    op.drop_index(
        op.f("ix_refunds_partial_version_end_transaction_id"),
        table_name="refunds_partial_version",
    )
    op.drop_table("refunds_partial_version")
    # ### end Alembic commands ###
