"""empty message

Revision ID: f61dd2efb63c
Revises: 23ccec8375c3
Create Date: 2025-05-16 12:11:53.287854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# Note you may see foreign keys with distribution_codes_history
# For disbursement_distribution_code_id, service_fee_distribution_code_id
# Please ignore those lines and don't include in migration.

revision = 'f61dd2efb63c'
down_revision = '23ccec8375c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribution_codes_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'distribution_codes_history', ['disbursement_distribution_code_id'], ['distribution_code_id'])
        batch_op.create_foreign_key(None, 'distribution_codes_history', ['service_fee_distribution_code_id'], ['distribution_code_id'])

    with op.batch_alter_table('eft_refunds', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eft_refunds', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('distribution_codes_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
