"""empty message

Revision ID: 23ccec8375c3
Revises: ad4a7000010b
Create Date: 2025-05-16 09:30:26.426206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# Note you may see foreign keys with distribution_codes_history
# For disbursement_distribution_code_id, service_fee_distribution_code_id
# Please ignore those lines and don't include in migration.

revision = '23ccec8375c3'
down_revision = '0b7e98fdc955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('fee_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_on_price_list', sa.Boolean(), nullable=True, comment='Flag to indicate if the fee schedule should be shown on the price list'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_schedules', schema=None) as batch_op:
        batch_op.drop_column('show_on_price_list')

    with op.batch_alter_table('eft_refunds', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('distribution_codes_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###