"""add_audit_versioning_to_admin_tables

Revision ID: cb622dbbf69d
Revises: 9eca4bd8c832
Create Date: 2026-05-04 10:45:23.162098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# Note you may see foreign keys with distribution_codes_history
# For disbursement_distribution_code_id, service_fee_distribution_code_id
# Please ignore those lines and don't include in migration.

revision = 'cb622dbbf69d'
down_revision = '9eca4bd8c832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corp_types_history',
    sa.Column('code', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(length=200), autoincrement=False, nullable=False),
    sa.Column('bcol_code_full_service_fee', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('bcol_code_partial_service_fee', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('bcol_code_no_service_fee', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('bcol_staff_fee_code', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('is_online_banking_allowed', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('has_partner_disbursements', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('batch_type', sa.String(length=2), autoincrement=False, nullable=True),
    sa.Column('product', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_methods', sa.ARRAY(sa.String()), autoincrement=False, nullable=True),
    sa.Column('refund_approval', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('created_name', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_name', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code', 'version'),
    sqlite_autoincrement=True
    )
    op.create_table('fee_codes_history',
    sa.Column('code', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('created_name', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_name', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code', 'version'),
    sqlite_autoincrement=True
    )
    op.create_table('filing_types_history',
    sa.Column('code', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(length=200), autoincrement=False, nullable=False),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('created_name', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_name', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code', 'version'),
    sqlite_autoincrement=True
    )
    op.create_table('fee_schedules_history',
    sa.Column('fee_schedule_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('filing_type_code', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('corp_type_code', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('fee_code', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('fee_start_date', sa.Date(), autoincrement=False, nullable=False),
    sa.Column('fee_end_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('future_effective_fee_code', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('priority_fee_code', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('service_fee_code', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('variable', sa.Boolean(), autoincrement=False, nullable=True, comment='Flag to indicate if the fee is variable'),
    sa.Column('show_on_pricelist', sa.Boolean(), autoincrement=False, nullable=False),
    sa.Column('gst_added', sa.Boolean(), autoincrement=False, nullable=True, comment='Flag to indicate if GST is added for this fee schedule'),
    sa.Column('created_on', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('updated_on', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('created_name', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_name', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corp_type_code'], ['corp_types.code'], ),
    sa.ForeignKeyConstraint(['fee_code'], ['fee_codes.code'], ),
    sa.ForeignKeyConstraint(['filing_type_code'], ['filing_types.code'], ),
    sa.ForeignKeyConstraint(['future_effective_fee_code'], ['fee_codes.code'], ),
    sa.ForeignKeyConstraint(['priority_fee_code'], ['fee_codes.code'], ),
    sa.ForeignKeyConstraint(['service_fee_code'], ['fee_codes.code'], ),
    sa.PrimaryKeyConstraint('fee_schedule_id', 'version')
    )

    with op.batch_alter_table('corp_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('fee_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('fee_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('filing_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))

    # Backfill existing rows before enforcing NOT NULL
    op.execute("UPDATE corp_types SET created_by = 'Alembic', created_on = now() WHERE created_by IS NULL")
    op.execute("UPDATE fee_codes SET created_by = 'Alembic', created_on = now() WHERE created_by IS NULL")
    op.execute("UPDATE filing_types SET created_by = 'Alembic', created_on = now() WHERE created_by IS NULL")
    op.execute("UPDATE fee_schedules SET created_by = 'Alembic', created_on = now() WHERE created_by IS NULL")

    # Enforce NOT NULL now that existing rows are backfilled
    op.alter_column('corp_types', 'created_by', nullable=False)
    op.alter_column('corp_types', 'created_on', nullable=False)
    op.alter_column('fee_codes', 'created_by', nullable=False)
    op.alter_column('fee_codes', 'created_on', nullable=False)
    op.alter_column('filing_types', 'created_by', nullable=False)
    op.alter_column('filing_types', 'created_on', nullable=False)
    op.alter_column('fee_schedules', 'created_by', nullable=False)
    op.alter_column('fee_schedules', 'created_on', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filing_types', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('updated_name')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_name')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    with op.batch_alter_table('fee_schedules', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('updated_name')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_name')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    with op.batch_alter_table('fee_codes', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('updated_name')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_name')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    with op.batch_alter_table('corp_types', schema=None) as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('updated_name')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_name')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('created_on')

    op.drop_table('fee_schedules_history')
    op.drop_table('filing_types_history')
    op.drop_table('fee_codes_history')
    op.drop_table('corp_types_history')
    # ### end Alembic commands ###
