"""adding_routing_slip_comments

Revision ID: 20a426ebbc9b
Revises: 4cb0dc8e0013
Create Date: 2021-10-25 14:02:06.208386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a426ebbc9b'
down_revision = '4cb0dc8e0013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.String(length=4096), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('routing_slip_number', sa.String(), nullable=True),
    sa.Column('submitter_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['routing_slip_number'], ['routing_slips.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_routing_slip_number'), 'comments', ['routing_slip_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_routing_slip_number'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
