"""versioning_to_payment_account

Revision ID: 20f0cfd54e81
Revises: 1283463d3b4a
Create Date: 2020-09-17 12:26:33.052069

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op


# revision identifiers, used by Alembic.
revision = "20f0cfd54e81"
down_revision = "1283463d3b4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("verb", sa.Unicode(length=255), nullable=True),
        sa.Column("transaction_id", sa.BigInteger(), nullable=False),
        sa.Column("data", sqlalchemy_utils.types.json.JSONType(), nullable=True),
        sa.Column("object_type", sa.String(length=255), nullable=True),
        sa.Column("object_id", sa.BigInteger(), nullable=True),
        sa.Column("object_tx_id", sa.BigInteger(), nullable=True),
        sa.Column("target_type", sa.String(length=255), nullable=True),
        sa.Column("target_id", sa.BigInteger(), nullable=True),
        sa.Column("target_tx_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_transaction_id"), "activity", ["transaction_id"], unique=False
    )
    op.create_table(
        "payment_account_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_account_id", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "auth_account_name",
            sa.String(length=250),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "payment_method", sa.String(length=10), autoincrement=False, nullable=True
        ),
        sa.Column(
            "bcol_user_id", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "bcol_account", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "statement_notification_enabled",
            sa.Boolean(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("running_balance", sa.Float(), autoincrement=False, nullable=True),
        sa.Column("credit", sa.Float(), autoincrement=False, nullable=True),
        sa.Column("billable", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_payment_account_version_auth_account_id"),
        "payment_account_version",
        ["auth_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_account_version_bcol_account"),
        "payment_account_version",
        ["bcol_account"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_account_version_bcol_user_id"),
        "payment_account_version",
        ["bcol_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_account_version_end_transaction_id"),
        "payment_account_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_account_version_operation_type"),
        "payment_account_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_account_version_transaction_id"),
        "payment_account_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "transaction",
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("remote_addr", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    op.drop_index(
        op.f("ix_payment_account_version_transaction_id"),
        table_name="payment_account_version",
    )
    op.drop_index(
        op.f("ix_payment_account_version_operation_type"),
        table_name="payment_account_version",
    )
    op.drop_index(
        op.f("ix_payment_account_version_end_transaction_id"),
        table_name="payment_account_version",
    )
    op.drop_index(
        op.f("ix_payment_account_version_bcol_user_id"),
        table_name="payment_account_version",
    )
    op.drop_index(
        op.f("ix_payment_account_version_bcol_account"),
        table_name="payment_account_version",
    )
    op.drop_index(
        op.f("ix_payment_account_version_auth_account_id"),
        table_name="payment_account_version",
    )
    op.drop_table("payment_account_version")
    op.drop_index(op.f("ix_activity_transaction_id"), table_name="activity")
    op.drop_table("activity")
    # ### end Alembic commands ###
