"""bcol_staff_payment

Revision ID: 27206a9634ad
Revises: e8edc889072d
Create Date: 2020-07-20 12:51:26.986137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27206a9634ad'
down_revision = 'e8edc889072d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('dat_number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_invoice_dat_number'), 'invoice', ['dat_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_dat_number'), table_name='invoice')
    op.drop_column('invoice', 'dat_number')
    # ### end Alembic commands ###
