"""Add in disbursement_date, that we we know exactly when a transaction was disbursed.

Revision ID: 286acad5d366
Revises: 39c2491d0a07
Create Date: 2023-01-30 10:31:10.226000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "286acad5d366"
down_revision = "39c2491d0a07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices", sa.Column("disbursement_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "disbursement_date")
    # ### end Alembic commands ###
