"""payment_tables_changes

Revision ID: 2cd94d9fefcb
Revises: 0420566ac811
Create Date: 2019-05-29 13:09:39.448238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cd94d9fefcb'
down_revision = '0420566ac811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transaction',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status_code', sa.String(length=10), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('redirect_url', sa.String(length=200), nullable=False),
    sa.Column('pay_system_url', sa.String(length=500), nullable=True),
    sa.Column('transaction_start_time', sa.DateTime(), nullable=False),
    sa.Column('transaction_end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['status_code'], ['status_code.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fee_item')
    op.drop_column('payment', 'paid')
    op.drop_column('payment', 'total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('paid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('fee_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filing_fees', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fee_schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('processing_fees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_fees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('gst', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pst', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fee_schedule_id'], ['fee_schedule.fee_schedule_id'], name='fee_item_fee_schedule_id_fkey'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name='fee_item_invoice_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fee_item_pkey')
    )
    op.drop_table('payment_transaction')
    # ### end Alembic commands ###
