"""ppr_fee_codes

Revision ID: 2efd8e2b92a1
Revises: 7c127b25168f
Create Date: 2021-03-16 10:49:56.185103

"""
from datetime import datetime, timezone

from alembic import op
from sqlalchemy import Date, Float, String
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = '2efd8e2b92a1'
down_revision = '7c127b25168f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update filing_types set description='PPR Search' where code='SERCH'")
    op.execute("update filing_types set description='PPR Registration (year)' where code='FSREG'")
    op.execute("update filing_types set description='PPR Registration (infinity)' where code='INFRG'")

    fee_code_table = table("fee_codes", column("code", String), column("amount", Float))

    filing_type_table = table(
        "filing_types", column("code", String), column("description", String)
    )

    fee_schedule_table = table(
        "fee_schedules",
        column("filing_type_code", String),
        column("corp_type_code", String),
        column("fee_code", String),
        column("fee_start_date", Date),
        column("fee_end_date", Date),
        column("future_effective_fee_code", String),
        column("priority_fee_code", String),
        column("service_fee_code", String)
    )

    # Fee Codes
    op.bulk_insert(
        fee_code_table, [
            {"code": "EN114", "amount": 10}
        ]
    )

    # Filing Types
    op.bulk_insert(
        filing_type_table,
        [
            {'code': 'FLREG', 'description': 'PPR Registration under the Family Law Act'},
            {'code': 'RLREG', 'description': "PPR Repairer's Lien"},
            {'code': 'FSREN', 'description': 'PPR Renewal'},
            {'code': 'INFRN', 'description': 'PPR Infinity Renewal'},
            {'code': 'FSCHG', 'description': 'PPR Change or Amendment'}

        ]
    )

    op.bulk_insert(
        fee_schedule_table,
        [
            {
                "filing_type_code": "FLREG",
                "corp_type_code": "PPR",
                "fee_code": "EN114",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": None,
                "service_fee_code": "TRF01"
            },
            {
                "filing_type_code": "RLREG",
                "corp_type_code": "PPR",
                "fee_code": "EN111",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": None,
                "service_fee_code": "TRF01"
            },
            {
                "filing_type_code": "FSREN",
                "corp_type_code": "PPR",
                "fee_code": "EN111",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": None,
                "service_fee_code": "TRF01"
            },
            {
                "filing_type_code": "INFRN",
                "corp_type_code": "PPR",
                "fee_code": "EN112",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": "FUT01",
                "priority_fee_code": None,
                "service_fee_code": "TRF01"
            },
            {
                "filing_type_code": "FSCHG",
                "corp_type_code": "PPR",
                "fee_code": "EN114",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": None,
                "service_fee_code": "TRF01"
            }
        ],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("delete from fee_schedules where filing_type_code in ('FSCHG', 'INFRN', 'FSREN', 'RLREG', 'FLREG')")
    op.execute("delete from filing_types where code in ('FSCHG', 'INFRN', 'FSREN', 'RLREG', 'FLREG')")
    op.execute("delete from fee_codes where code = 'EN114'")
    # ### end Alembic commands ###
