"""payment_transaction_changes

Revision ID: 2ffe44097a0e
Revises: 2cd94d9fefcb
Create Date: 2019-05-29 13:35:11.546733

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "2ffe44097a0e"
down_revision = "2cd94d9fefcb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment_transaction",
        sa.Column("client_system_url", sa.String(length=500), nullable=False),
    )
    op.drop_column("payment_transaction", "redirect_url")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment_transaction",
        sa.Column(
            "redirect_url", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("payment_transaction", "client_system_url")
    # ### end Alembic commands ###
