"""empty message

Revision ID: 320f9f89eb68
Revises: 70af1f70f6bf
Create Date: 2020-10-16 13:16:32.313350

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "320f9f89eb68"
down_revision = "70af1f70f6bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payment_account",
        "payment_method",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=15),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_account_version",
        "payment_method",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=15),
        existing_nullable=True,
        autoincrement=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payment_account_version",
        "payment_method",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
        autoincrement=False,
    )
    op.alter_column(
        "payment_account",
        "payment_method",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )

    # ### end Alembic commands ###
