"""create direct_pay_payment_account

Revision ID: 3832dfa020a8
Revises: 7a316d48f9ae
Create Date: 2020-07-28 14:02:13.323957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3832dfa020a8'
down_revision = '7a316d48f9ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_pay_payment_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corp_number', sa.String(length=20), nullable=True),
    sa.Column('corp_type_code', sa.String(length=10), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['payment_account.id'], ),
    sa.ForeignKeyConstraint(['corp_type_code'], ['corp_type.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_pay_payment_account_account_id'), 'direct_pay_payment_account', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_direct_pay_payment_account_account_id'), table_name='direct_pay_payment_account')
    op.drop_table('direct_pay_payment_account')
    # ### end Alembic commands ###
