"""create direct_pay_payment_account

Revision ID: 39a97401040c
Revises: e385e278cf3e
Create Date: 2020-07-29 12:20:53.748750

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import String
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = "39a97401040c"
down_revision = "e385e278cf3e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    payment_method_table = table(
        "payment_method", column("code", String), column("description", String)
    )

    op.bulk_insert(
        payment_method_table, [{"code": "DIRECT_PAY", "description": "Credit Card"}]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM payment_method where code="DIRECT_PAY"')
    # ### end Alembic commands ###
