"""online_banking_flags

Revision ID: 41f76e6c82eb
Revises: 15682073c535
Create Date: 2021-01-06 09:11:05.344255

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "41f76e6c82eb"
down_revision = "15682073c535"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "corp_type", sa.Column("is_online_banking_allowed", sa.Boolean(), nullable=True)
    )
    op.execute("update corp_type set is_online_banking_allowed=true")
    op.execute(
        "update corp_type set is_online_banking_allowed=false where code in ('NRO', 'VS')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("corp_type", "is_online_banking_allowed")
    # ### end Alembic commands ###
