"""add account_id to statements

Revision ID: 444df7ad2d80
Revises: 7e51d3ce4005
Create Date: 2020-08-18 12:00:41.037140

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "444df7ad2d80"
down_revision = "7e51d3ce4005"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "statement", sa.Column("payment_account_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_statement_payment_account_id"),
        "statement",
        ["payment_account_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "statement", "payment_account", ["payment_account_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "statement", type_="foreignkey")
    op.drop_index(op.f("ix_statement_payment_account_id"), table_name="statement")
    op.drop_column("statement", "payment_account_id")
    # ### end Alembic commands ###
