"""adding_routing_slip_number

Revision ID: 4a6ddf932b62
Revises: 8314eaebde37
Create Date: 2019-10-17 13:16:25.428291

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "4a6ddf932b62"
down_revision = "8314eaebde37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice", sa.Column("routing_slip", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoice", "routing_slip")
    # ### end Alembic commands ###
