"""changes_for_cg_ejv

Revision ID: 57e320b52b2d
Revises: 6f0fe9f23d8c
Create Date: 2021-02-04 13:42:12.936898

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '57e320b52b2d'
down_revision = '6f0fe9f23d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corp_types', sa.Column('batch_type', sa.String(length=2), nullable=True))
    op.add_column('ejv_files', sa.Column('disbursement_status_code', sa.String(length=20), nullable=True))
    op.add_column('ejv_files', sa.Column('feedback_file_ref', sa.String(), nullable=True))
    op.create_foreign_key('corp_type_disbursement_status_code_fk', 'ejv_files', 'disbursement_status_codes',
                          ['disbursement_status_code'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('corp_type_disbursement_status_code_fk', 'ejv_files', type_='foreignkey')
    op.drop_column('ejv_files', 'feedback_file_ref')
    op.drop_column('ejv_files', 'disbursement_status_code')
    op.drop_column('corp_types', 'batch_type')

    # ### end Alembic commands ###
