"""fas_table

Revision ID: 5b1ae231f7d2
Revises: 4c3b8d61d200
Create Date: 2021-07-06 11:11:29.386829

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import String
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision = "5b1ae231f7d2"
down_revision = "4c3b8d61d200"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    payment_method_table = table(
        "payment_methods", column("code", String), column("description", String)
    )

    op.bulk_insert(
        payment_method_table,
        [
            {"code": "CASH", "description": "Cash payment"},
            {"code": "CHEQUE", "description": "Cheque payment"},
        ],
    )

    payment_system_table = table(
        "payment_systems", column("code", String), column("description", String)
    )

    op.bulk_insert(
        payment_system_table, [{"code": "FAS", "description": "Fee Accounting System"}]
    )

    rs_status_table = op.create_table(
        "routing_slip_status_codes",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.bulk_insert(
        rs_status_table,
        [
            {"code": "ACTIVE", "description": "Active"},
            {"code": "COMPLETE", "description": "Completed"},
            {"code": "BOUNCED", "description": "Bounced"},
            {"code": "NSF", "description": "Non Sufficient Fund"},
            {"code": "REFUND", "description": "Refund"},
            {"code": "LAST", "description": "Last Service"},
            {"code": "HOLD", "description": "On Hold"},
        ],
    )

    op.create_table(
        "routing_slips",
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(), nullable=True),
        sa.Column("payment_account_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("total", sa.Numeric(), nullable=True),
        sa.Column("remaining_amount", sa.Numeric(), nullable=True),
        sa.Column("created_by", sa.String(length=50), nullable=False),
        sa.Column("created_name", sa.String(length=100), nullable=True),
        sa.Column("updated_by", sa.String(length=50), nullable=True),
        sa.Column("updated_name", sa.String(length=50), nullable=True),
        sa.Column("routing_slip_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_account_id"],
            ["payment_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status"],
            ["routing_slip_status_codes.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.alter_column("payment_accounts", "auth_account_name", new_column_name="name")
    op.alter_column(
        "payment_accounts_version", "auth_account_name", new_column_name="name"
    )

    op.add_column(
        "payments",
        sa.Column(
            "cheque_receipt_number",
            sa.String(length=50),
            nullable=True,
            comment="Cheque or cash receipt number",
        ),
    )
    op.add_column(
        "payments",
        sa.Column(
            "is_routing_slip",
            sa.Boolean(),
            nullable=True,
            comment="Is the payment created as part of FAS by FAS User",
        ),
    )
    op.alter_column(
        "payments",
        "completed_on",
        new_column_name="payment_date",
        comment="Date of payment",
    )

    op.alter_column(
        "payments",
        "invoice_number",
        existing_type=sa.VARCHAR(length=50),
        comment="CFS Invoice number",
        existing_nullable=True,
    )
    op.alter_column(
        "payments",
        "receipt_number",
        existing_type=sa.VARCHAR(length=50),
        comment="CFS Receipt number",
        existing_nullable=True,
    )
    op.alter_column(
        "payments",
        "paid_amount",
        existing_type=sa.NUMERIC(),
        comment="Amount PAID as part of payment",
        existing_nullable=True,
    )
    op.alter_column(
        "payments",
        "created_by",
        existing_type=sa.VARCHAR(length=50),
        comment="Created user name, SYSTEM if job creates the record",
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_payments_cheque_receipt_number"),
        "payments",
        ["cheque_receipt_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("payments", "payment_date", new_column_name="completed_on")
    op.drop_index(op.f("ix_payments_cheque_receipt_number"), table_name="payments")
    op.alter_column(
        "payments",
        "created_by",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Created user name, SYSTEM if job creates the record",
        existing_nullable=True,
    )
    op.alter_column(
        "payments",
        "paid_amount",
        existing_type=sa.NUMERIC(),
        comment=None,
        existing_comment="Amount PAID as part of payment",
        existing_nullable=True,
    )
    op.alter_column(
        "payments",
        "receipt_number",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="CFS Receipt number",
        existing_nullable=True,
    )
    op.alter_column(
        "payments",
        "invoice_number",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="CFS Invoice number",
        existing_nullable=True,
    )
    op.drop_column("payments", "is_routing_slip")
    op.drop_column("payments", "cheque_receipt_number")
    op.alter_column("payment_accounts", "name", new_column_name="auth_account_name")
    op.alter_column(
        "payment_accounts_version", "name", new_column_name="auth_account_name"
    )
    op.drop_table("routing_slips")
    op.drop_table("routing_slip_status_codes")
    # ### end Alembic commands ###
