"""jv_feedback_changes

Revision ID: 5fbc9aaa34a1
Revises: ebee125e6877
Create Date: 2021-02-19 15:05:03.741562

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5fbc9aaa34a1'
down_revision = 'ebee125e6877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_codes', sa.Column('stop_ejv', sa.Boolean(), nullable=True))
    op.add_column('ejv_files', sa.Column('message', sa.String(), nullable=True))
    op.add_column('ejv_headers', sa.Column('message', sa.String(), nullable=True))
    op.add_column('ejv_invoice_links', sa.Column('disbursement_status_code', sa.String(length=20), nullable=True))
    op.add_column('ejv_invoice_links', sa.Column('message', sa.String(), nullable=True))
    op.create_foreign_key('ejv_invoice_link_disbursement_status_code_fk', 'ejv_invoice_links',
                          'disbursement_status_codes', ['disbursement_status_code'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ejv_invoice_link_disbursement_status_code_fk', 'ejv_invoice_links', type_='foreignkey')
    op.drop_column('ejv_invoice_links', 'message')
    op.drop_column('ejv_invoice_links', 'disbursement_status_code')
    op.drop_column('ejv_headers', 'message')
    op.drop_column('ejv_files', 'message')
    op.drop_column('distribution_codes', 'stop_ejv')

    # ### end Alembic commands ###
