"""pay_table_changes

Revision ID: 6a2a6b85e134
Revises: 170ee3d24bcf
Create Date: 2019-05-28 10:35:34.394843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2a6b85e134'
down_revision = '170ee3d24bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'paid')
    op.drop_column('payment', 'total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('paid', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
