"""entity/12312
Business Search - Add Corp Type Code, Fee Schedule, Distribution Code

Revision ID: 6a6b042b831a
Revises: e748b5c19247
Create Date: 2022-05-24 21:46:54.030721

"""

from datetime import datetime, timezone
from re import M

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Date, Float, Integer, Boolean, String
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = "6a6b042b831a"
down_revision = "e748b5c19247"
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    corp_type_table = table(
        "corp_types",
        column("code", String),
        column("description", String),
        column("is_online_banking_allowed", Boolean),
        column("product", String),
    )

    filing_type_table = table(
        "filing_types", column("code", String), column("description", String)
    )

    fee_schedule_table = table(
        "fee_schedules",
        column("filing_type_code", String),
        column("corp_type_code", String),
        column("fee_code", String),
        column("fee_start_date", Date),
        column("fee_end_date", Date),
        column("service_fee_code", String),
        column("variable", Boolean),
    )

    distribution_code_table = table(
        "distribution_codes",
        column("created_on", Date),
        column("name", String),
        column("client", String),
        column("responsibility_centre", String),
        column("service_line", String),
        column("stob", String),
        column("project_code", String),
        column("start_date", Date),
        column("created_by", String),
        column("product_mapping", String),
    )

    distribution_code_link_table = table(
        "distribution_code_links",
        column("distribution_code_id", Integer),
        column("fee_schedule_id", Integer),
    )

    # Product code/corp type
    op.bulk_insert(
        corp_type_table,
        [
            {
                "code": "BUS",
                "description": "Business Search",
                "is_online_banking_allowed": False,
                "product": "BUSINESS_SEARCH",
            }
        ],
    )

    # Filing Types
    op.bulk_insert(
        filing_type_table, [{"code": "BSRCH", "description": "Business Search"}]
    )

    # Fee Schedules
    op.bulk_insert(
        fee_schedule_table,
        [
            {
                "filing_type_code": "BSRCH",
                "corp_type_code": "BUS",
                "fee_code": "EN110",  # 7.00
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "service_fee_code": "TRF01",  # $1.50 default
            }
        ],
    )

    op.bulk_insert(
        distribution_code_table,
        [
            {
                "created_on": datetime.now(tz=timezone.utc),
                "name": "Corporate Registry - Searches",
                "client": "112",
                "responsibility_centre": "32363",
                "service_line": "34725",
                "stob": "4375",
                "project_code": "3200056",
                "start_date": datetime.now(tz=timezone.utc),
                "created_by": "Alembic",
            }
        ],
    )

    distribution_code_id_query = "select distribution_code_id from distribution_codes where name = 'Corporate Registry - Searches' and created_by = 'Alembic'"
    conn = op.get_bind()
    res = conn.execute(sa.text(distribution_code_id_query))
    distribution_code_id = res.fetchall()[0][0]
    new_codes = ("BSRCH",)
    distr_code_link_values = []
    for new_code in new_codes:
        res = conn.execute(
            sa.text(
                f"select fee_schedule_id from fee_schedules where filing_type_code='{new_code}' and corp_type_code='BUS'"
            )
        )
        fee_schedule_id = res.fetchall()[0][0]
        distr_code_link_values.append(
            {
                "distribution_code_id": distribution_code_id,
                "fee_schedule_id": fee_schedule_id,
            }
        )
    op.bulk_insert(distribution_code_link_table, distr_code_link_values)
    # ### end Alembic commands ###

    def downgrade():
        # ### commands auto generated by Alembic - please adjust! ###
        op.execute(
            "DELETE FROM distribution_code_links where fee_schedule_id in (select fee_schedule_id from fee_schedules where corp_type_code='BUS' and filing_type_code in ('BSRCH'))"
        )
        op.execute("delete from fee_schedules where filing_type_code in ('BSRCH') ")
        op.execute("delete from filing_types where code in ('BSRCH') ")
        op.execute("delete from corp_types where code in ('BUS') ")
        op.execute(
            "delete from distribution_codes where name = 'Corporate Registry - Searches' and created_by = 'Alembic'"
        )
        # ### end Alembic commands ###
