"""adding_error_codes_table

Revision ID: 6ba89cd39cc8
Revises: 8eac44955fb6
Create Date: 2020-04-14 12:36:57.094459

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6ba89cd39cc8"
down_revision = "8eac44955fb6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    error_code_table = op.create_table(
        "error_code",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("detail", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.bulk_insert(
        error_code_table,
        [
            {
                "code": "INVALID_CORP_OR_FILING_TYPE",
                "title": "Invalid Request",
                "detail": "Invalid Corp Type or Filing Type.",
            },
            {
                "code": "INVALID_PAYMENT_ID",
                "title": "Invalid Request",
                "detail": "Invalid Payment Identifier.",
            },
            {
                "code": "INVALID_TRANSACTION",
                "title": "Invalid Request",
                "detail": "Transaction is already completed.",
            },
            {
                "code": "INVALID_REDIRECT_URI",
                "title": "Invalid Request",
                "detail": "Invalid redirect url.",
            },
            {
                "code": "INVALID_TRANSACTION_ID",
                "title": "Invalid Request",
                "detail": "Invalid transaction identifier.",
            },
            {
                "code": "INVALID_ACCOUNT_ID",
                "title": "Invalid Request",
                "detail": "Invalid account identifier.",
            },
            {
                "code": "COMPLETED_PAYMENT",
                "title": "Invalid Request",
                "detail": "Payment is already completed.",
            },
            {
                "code": "CANCELLED_PAYMENT",
                "title": "Invalid Request",
                "detail": "Payment is already cancelled.",
            },
            {
                "code": "INVALID_INVOICE_ID",
                "title": "Invalid Request",
                "detail": "Invalid invoice identifier.",
            },
            {
                "code": "FEE_OVERRIDE_NOT_ALLOWED",
                "title": "Invalid Request",
                "detail": "Fee override is not allowed.",
            },
            {
                "code": "INCOMPLETE_ACCOUNT_SETUP",
                "title": "Invalid Request",
                "detail": "Premium account setup is incomplete.",
            },
            {
                "code": "BCOL_ACCOUNT_CLOSED",
                "title": "BC Online account closed",
                "detail": "This BC Online account has been closed. "
                "Please contact the help desk. "
                "\nSERVICE BC HELP DESK: "
                "\nToll-free: 1-800-663-6102 (Canada and USA only)"
                "\nFax: (250) 952-6115"
                "\nEmail: bcolhelp@gov.bc.ca.",
            },
            {
                "code": "BCOL_USER_REVOKED",
                "title": "BC Online user revoked",
                "detail": "This BC Online user has been revoked. "
                "Please contact the help desk. "
                "\nSERVICE BC HELP DESK: "
                "\nToll-free: 1-800-663-6102 (Canada and USA only)"
                "\nFax: (250) 952-6115"
                "\nEmail: bcolhelp@gov.bc.ca.",
            },
            {
                "code": "BCOL_ACCOUNT_REVOKED",
                "title": "BC Online account revoked",
                "detail": "This BC Online account has been revoked. "
                "Please contact the help desk. "
                "\nSERVICE BC HELP DESK: "
                "\nToll-free: 1-800-663-6102 (Canada and USA only)"
                "\nFax: (250) 952-6115"
                "\nEmail: bcolhelp@gov.bc.ca.",
            },
            {
                "code": "BCOL_UNAVAILABLE",
                "title": "BC Online system not available",
                "detail": "BC Online system is not available. Please try again later.",
            },
            {
                "code": "BCOL_ERROR",
                "title": "Error",
                "detail": "An error occurred during the BC Online transaction. "
                "Please contact the help desk. "
                "\nSERVICE BC HELP DESK: "
                "\nToll-free: 1-800-663-6102 (Canada and USA only)"
                "\nFax: (250) 952-6115"
                "\nEmail: bcolhelp@gov.bc.ca.",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("error_code")
    # ### end Alembic commands ###
