"""account_fee

Revision ID: 7649a31bfe39
Revises: 9335f4e0aa22
Create Date: 2021-04-22 12:11:08.896138

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Float, String
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = "7649a31bfe39"
down_revision = "9335f4e0aa22"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_fees",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("apply_filing_fees", sa.Boolean(), nullable=True),
        sa.Column("service_fee_code", sa.String(length=10), nullable=True),
        sa.Column("product", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["payment_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_fee_code"],
            ["fee_codes.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_fees_account_id"), "account_fees", ["account_id"], unique=False
    )
    op.add_column(
        "corp_types", sa.Column("product", sa.String(length=20), nullable=True)
    )

    # Insert fee code for the $1
    fee_code_table = table("fee_codes", column("code", String), column("amount", Float))
    op.bulk_insert(fee_code_table, [{"code": "TRF02", "amount": 1}])
    op.execute(
        "update corp_types set product='BUSINESS' where code in ('BC', 'CP', 'BEN', 'ULC', 'BCR')"
    )
    op.execute("update corp_types set product='VS' where code in ('VS')")
    op.execute("update corp_types set product='PPR' where code in ('PPR')")
    op.execute("update corp_types set product='NRO' where code in ('NRO')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("corp_types", "product")
    op.drop_index(op.f("ix_account_fees_account_id"), table_name="account_fees")
    op.drop_table("account_fees")
    op.execute("delete from fee_codes where code='TRF02'")
    op.execute("update corp_types set product=null")
    # ### end Alembic commands ###
