"""waived_fee_changes

Revision ID: 78951cf14ae9
Revises: 7d16423bc042
Create Date: 2020-01-24 11:29:27.828781

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "78951cf14ae9"
down_revision = "7d16423bc042"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment_line_item", sa.Column("waived_by", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "payment_line_item", sa.Column("waived_fees", sa.Float(), nullable=True)
    )
    op.alter_column(
        "payment_line_item",
        "filing_fees",
        existing_type=sa.INTEGER,
        type_=sa.FLOAT,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment_line_item", "waived_fees")
    op.drop_column("payment_line_item", "waived_by")
    # ### end Alembic commands ###
