"""invoice_amount_to_payment

Revision ID: 7c19ee3a58aa
Revises: 086e16326076
Create Date: 2020-11-10 09:07:14.336944

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import String
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = "7c19ee3a58aa"
down_revision = "086e16326076"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("payment", "amount", new_column_name="paid_amount")
    op.add_column("payment", sa.Column("invoice_amount", sa.Numeric(), nullable=True))
    # lookup the invoice table 'total' field by linking with invoice_reference
    conn = op.get_bind()
    res = conn.execute(
        sa.text(
            "select inv.total, inv_ref.invoice_number, inv.payment_account_id "
            "from invoice inv, invoice_reference inv_ref where inv.id=inv_ref.invoice_id"
        )
    )

    invoices = res.fetchall()

    for inv in invoices:
        total = inv[0]
        inv_number = inv[1]
        pay_account_id = inv[2]
        # Update payment method in invoice
        op.execute(
            f"update payment set invoice_amount={total}, payment_account_id={pay_account_id}  where invoice_number='{inv_number}'"
        )

    status_code_table = table(
        "invoice_status_code", column("code", String), column("description", String)
    )

    op.bulk_insert(
        status_code_table, [{"code": "PARTIAL_PAID", "description": "Partially Paid"}]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("payment", "paid_amount", new_column_name="amount")
    op.drop_column("payment", "invoice_amount")
    op.execute("delete from invoice_status_code where code='PARTIAL_PAID'")
    # ### end Alembic commands ###
