"""statement_settings

Revision ID: 7e51d3ce4005
Revises: 567df104d26c
Create Date: 2020-08-18 10:04:08.532357

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7e51d3ce4005"
down_revision = "567df104d26c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statement_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("frequency", sa.String(length=50), nullable=True),
        sa.Column("payment_account_id", sa.Integer(), nullable=True),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_account_id"],
            ["payment_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_statement_settings_frequency"),
        "statement_settings",
        ["frequency"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statement_settings_payment_account_id"),
        "statement_settings",
        ["payment_account_id"],
        unique=False,
    )
    op.add_column("statement", sa.Column("created_on", sa.Date(), nullable=False))
    op.add_column(
        "statement", sa.Column("statement_settings_id", sa.Integer(), nullable=True)
    )
    op.alter_column("statement", "to_date", existing_type=sa.DATE(), nullable=False)
    op.create_index(
        op.f("ix_statement_statement_settings_id"),
        "statement",
        ["statement_settings_id"],
        unique=False,
    )
    op.drop_index("ix_statement_payment_account_id", table_name="statement")
    op.drop_index("ix_statement_status", table_name="statement")
    op.drop_constraint(
        "statement_payment_account_id_fkey", "statement", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "statement", "statement_settings", ["statement_settings_id"], ["id"]
    )
    op.drop_column("statement", "status")
    op.drop_column("statement", "payment_account_id")
    op.add_column(
        "statement_invoices", sa.Column("invoice_id", sa.Integer(), nullable=False)
    )
    op.drop_index("ix_statement_invoices_status", table_name="statement_invoices")
    op.drop_constraint(
        "statement_invoices_inovice_id_fkey", "statement_invoices", type_="foreignkey"
    )
    op.create_foreign_key(None, "statement_invoices", "invoice", ["invoice_id"], ["id"])
    op.drop_column("statement_invoices", "status")
    op.drop_column("statement_invoices", "inovice_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "statement_invoices",
        sa.Column("inovice_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "statement_invoices",
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "statement_invoices", type_="foreignkey")
    op.create_foreign_key(
        "statement_invoices_inovice_id_fkey",
        "statement_invoices",
        "invoice",
        ["inovice_id"],
        ["id"],
    )
    op.create_index(
        "ix_statement_invoices_status", "statement_invoices", ["status"], unique=False
    )
    op.drop_column("statement_invoices", "invoice_id")
    op.add_column(
        "statement",
        sa.Column(
            "payment_account_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "statement",
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "statement", type_="foreignkey")
    op.create_foreign_key(
        "statement_payment_account_id_fkey",
        "statement",
        "payment_account",
        ["payment_account_id"],
        ["id"],
    )
    op.create_index("ix_statement_status", "statement", ["status"], unique=False)
    op.create_index(
        "ix_statement_payment_account_id",
        "statement",
        ["payment_account_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_statement_statement_settings_id"), table_name="statement")
    op.alter_column("statement", "to_date", existing_type=sa.DATE(), nullable=True)
    op.drop_column("statement", "statement_settings_id")
    op.drop_column("statement", "created_on")
    op.drop_index(
        op.f("ix_statement_settings_payment_account_id"),
        table_name="statement_settings",
    )
    op.drop_index(
        op.f("ix_statement_settings_frequency"), table_name="statement_settings"
    )
    op.drop_table("statement_settings")
    # ### end Alembic commands ###
