"""Migrate some of the float fields to decimal.

Revision ID: 7fddd6ffe782
Revises: 9abc5b5245b6
Create Date: 2022-11-01 20:51:31.870370

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7fddd6ffe782"
down_revision = "9abc5b5245b6"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("drop view if exists rpt_invoices")
    op.execute("drop view if exists rpt_invoices_pli")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoices",
        "total",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "invoices",
        "paid",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "invoices",
        "refund",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "invoices",
        "service_fees",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_line_items",
        "filing_fees",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "payment_line_items",
        "priority_fees",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_line_items",
        "future_effective_fees",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_line_items",
        "gst",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_line_items",
        "pst",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_line_items",
        "total",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "payment_line_items",
        "waived_fees",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_line_items",
        "service_fees",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=19, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payment_line_items",
        "service_fees",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_line_items",
        "waived_fees",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_line_items",
        "total",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "payment_line_items",
        "pst",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_line_items",
        "gst",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_line_items",
        "future_effective_fees",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_line_items",
        "priority_fees",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_line_items",
        "filing_fees",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "invoices",
        "service_fees",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "invoices",
        "refund",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "invoices",
        "paid",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "invoices",
        "total",
        existing_type=sa.Numeric(precision=19, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
