"""payment_transaction_changes

Revision ID: 8432e683d12c
Revises: 0420566ac811
Create Date: 2019-05-27 10:50:19.220356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8432e683d12c'
down_revision = '0420566ac811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.add_column('payment_transaction', sa.Column('pay_system_url', sa.String(length=500), nullable=False))
    op.add_column('payment_transaction', sa.Column('payment_id', sa.Integer(), nullable=False))
    op.add_column('payment_transaction', sa.Column('redirect_url', sa.String(length=200), nullable=False))
    op.add_column('payment_transaction', sa.Column('transaction_end_time', sa.DateTime(), nullable=False))
    op.add_column('payment_transaction', sa.Column('transaction_start_time', sa.DateTime(), nullable=False))
    op.drop_constraint('payment_transaction_invoice_id_fkey', 'payment_transaction', type_='foreignkey')
    op.create_foreign_key(None, 'payment_transaction', 'payment', ['payment_id'], ['id'])
    op.drop_column('payment_transaction', 'invoice_id')
    op.drop_column('payment_transaction', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transaction', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('payment_transaction', sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment_transaction', type_='foreignkey')
    op.create_foreign_key('payment_transaction_invoice_id_fkey', 'payment_transaction', 'invoice', ['invoice_id'], ['id'])
    op.drop_column('payment_transaction', 'transaction_start_time')
    op.drop_column('payment_transaction', 'transaction_end_time')
    op.drop_column('payment_transaction', 'redirect_url')
    op.drop_column('payment_transaction', 'payment_id')
    op.drop_column('payment_transaction', 'pay_system_url')
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name='transaction_invoice_id_fkey'),
    sa.ForeignKeyConstraint(['status_code'], ['status_code.code'], name='transaction_status_code_fkey'),
    sa.PrimaryKeyConstraint('id', name='transaction_pkey')
    )
    # ### end Alembic commands ###
