"""empty message

Revision ID: 90afcc0d6d9f
Revises: f1ed292af77f
Create Date: 2021-01-18 11:12:04.728247

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from pay_api.models.cfs_account import CfsAccount


# revision identifiers, used by Alembic.
revision = "90afcc0d6d9f"
down_revision = "f1ed292af77f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cfs_account", "bank_account_number")
    op.drop_column("cfs_account_version", "bank_account_number")

    op.add_column(
        "cfs_account",
        sa.Column(
            "bank_account_number",
            sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_cfs_account_bank_account_number"),
        "cfs_account",
        ["bank_account_number"],
        unique=False,
    )

    op.drop_index("ix_cfs_account_bank_branch", table_name="cfs_account")
    op.drop_index("ix_cfs_account_bank_name", table_name="cfs_account")
    op.drop_column("cfs_account", "bank_branch")
    op.drop_column("cfs_account", "bank_name")
    op.add_column(
        "cfs_account_version",
        sa.Column(
            "bank_account_number",
            sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_cfs_account_version_bank_account_number"),
        "cfs_account_version",
        ["bank_account_number"],
        unique=False,
    )
    op.drop_index(
        "ix_cfs_account_version_bank_branch", table_name="cfs_account_version"
    )
    op.drop_index("ix_cfs_account_version_bank_name", table_name="cfs_account_version")
    op.drop_column("cfs_account_version", "bank_branch")
    op.drop_column("cfs_account_version", "bank_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "cfs_account_version",
        sa.Column(
            "bank_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "cfs_account_version",
        sa.Column(
            "bank_branch", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.create_index(
        "ix_cfs_account_version_bank_name",
        "cfs_account_version",
        ["bank_name"],
        unique=False,
    )
    op.create_index(
        "ix_cfs_account_version_bank_branch",
        "cfs_account_version",
        ["bank_branch"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_cfs_account_version_bank_account_number"),
        table_name="cfs_account_version",
    )
    op.drop_column("cfs_account_version", "bank_account_number")
    op.add_column(
        "cfs_account",
        sa.Column(
            "bank_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "cfs_account",
        sa.Column(
            "bank_branch", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.create_index(
        "ix_cfs_account_bank_name", "cfs_account", ["bank_name"], unique=False
    )
    op.create_index(
        "ix_cfs_account_bank_branch", "cfs_account", ["bank_branch"], unique=False
    )
    op.drop_index(op.f("ix_cfs_account_bank_account_number"), table_name="cfs_account")
    op.drop_column("cfs_account", "bank_account_number")

    # ### end Alembic commands ###
