"""transaction_fees_changes

Revision ID: 915528c15842
Revises: 1a4e08683cb2
Create Date: 2019-12-06 15:24:35.467854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '915528c15842'
down_revision = '1a4e08683cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corp_type', sa.Column('transaction_fee_code', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'corp_type', 'fee_code', ['transaction_fee_code'], ['code'])
    op.add_column('invoice', sa.Column('transaction_fees', sa.Float(), nullable=True))
    op.drop_column('payment_line_item', 'processing_fees')
    op.drop_column('payment_line_item', 'service_fees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_line_item', sa.Column('service_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('payment_line_item', sa.Column('processing_fees', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('invoice', 'transaction_fees')
    op.drop_constraint(None, 'corp_type', type_='foreignkey')
    op.drop_column('corp_type', 'transaction_fee_code')
    # ### end Alembic commands ###
