"""distribution_code_version

Revision ID: 9335f4e0aa22
Revises: 2efd8e2b92a1
Create Date: 2021-04-19 08:32:15.854032

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9335f4e0aa22"
down_revision = "2efd8e2b92a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distribution_codes_version",
        sa.Column("created_on", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_on", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "distribution_code_id", sa.Integer(), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.String(length=50), autoincrement=False, nullable=True),
        sa.Column("client", sa.String(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "responsibility_centre",
            sa.String(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "service_line", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("stob", sa.String(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "project_code", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("start_date", sa.Date(), autoincrement=False, nullable=True),
        sa.Column("end_date", sa.Date(), autoincrement=False, nullable=True),
        sa.Column("stop_ejv", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column(
            "service_fee_distribution_code_id",
            sa.Integer(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "disbursement_distribution_code_id",
            sa.Integer(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("account_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "created_by", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_name", sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_by", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_name", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("distribution_code_id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_distribution_codes_version_account_id"),
        "distribution_codes_version",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_distribution_codes_version_end_transaction_id"),
        "distribution_codes_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_distribution_codes_version_operation_type"),
        "distribution_codes_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_distribution_codes_version_transaction_id"),
        "distribution_codes_version",
        ["transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_distribution_codes_version_transaction_id"),
        table_name="distribution_codes_version",
    )
    op.drop_index(
        op.f("ix_distribution_codes_version_operation_type"),
        table_name="distribution_codes_version",
    )
    op.drop_index(
        op.f("ix_distribution_codes_version_end_transaction_id"),
        table_name="distribution_codes_version",
    )
    op.drop_index(
        op.f("ix_distribution_codes_version_account_id"),
        table_name="distribution_codes_version",
    )
    op.drop_table("distribution_codes_version")
    # ### end Alembic commands ###
