"""corp_type_table_changes

Revision ID: ac01134753e9
Revises: 41bf37772240
Create Date: 2020-02-12 09:47:54.469175

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ac01134753e9"
down_revision = "41bf37772240"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "corp_type", sa.Column("bcol_fee_code", sa.String(length=20), nullable=True)
    )
    op.execute("update corp_type set transaction_fee_code=NULL where code = 'CP'")
    op.execute(
        "update corp_type set bcol_fee_code='COOPVC01' where code in ('CP', 'BC')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("corp_type", "bcol_fee_code")
    op.execute("update corp_type set transaction_fee_code='TRF01' where code = 'CP'")
    # ### end Alembic commands ###
