"""entity_fee_codes

Revision ID: b7443d501d98
Revises: b624b5dbc9b9
Create Date: 2020-11-18 16:23:31.943979

"""

from datetime import datetime, timezone

from alembic import op
from sqlalchemy import Date, Float, String, text
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = "b7443d501d98"
down_revision = "b624b5dbc9b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    corp_type_table = table(
        "corp_type",
        column("code", String),
        column("description", String),
        column("bcol_fee_code", String),
        column("bcol_staff_fee_code", String),
    )
    op.bulk_insert(
        corp_type_table,
        [
            {
                "code": "ULC",
                "description": "Unlimited Liability Company",
                "bcol_fee_code": "BBCOMVC1",
                "bcol_staff_fee_code": "CBCOMVC1",
            }
        ],
    )
    # Patch to adjust manual code entries in other dev/test/prod
    conn = op.get_bind()
    res = conn.execute(text("select * from corp_type where code='BEN'"))
    ben_code = res.fetchall()
    if len(ben_code) == 0:
        # Insert BEN
        op.bulk_insert(
            corp_type_table,
            [
                {
                    "code": "BEN",
                    "description": "Benefit Company",
                    "bcol_fee_code": "BBCOMVC1",
                    "bcol_staff_fee_code": "CBCOMVC1",
                }
            ],
        )
        # Update all the fee_schedule with BEN
        op.execute(
            "update fee_schedule set corp_type_code = 'BEN' where corp_type_code = 'BC'"
        )

    fee_code_table = table("fee_code", column("code", String), column("amount", Float))

    filing_type_table = table(
        "filing_type", column("code", String), column("description", String)
    )

    fee_schedule_table = table(
        "fee_schedule",
        column("filing_type_code", String),
        column("corp_type_code", String),
        column("fee_code", String),
        column("fee_start_date", Date),
        column("fee_end_date", Date),
        column("future_effective_fee_code", String),
        column("priority_fee_code", String),
        column("service_fee_code", String),
    )

    # Fee Codes
    op.bulk_insert(fee_code_table, [{"code": "EN113", "amount": 1000}])

    # Filing Types
    op.bulk_insert(
        filing_type_table, [{"code": "TRANS", "description": "Transition Application"}]
    )

    op.bulk_insert(
        fee_schedule_table,
        [
            {
                "filing_type_code": "TRANS",
                "corp_type_code": "BC",
                "fee_code": "EN107",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": None,
                "service_fee_code": None,
            },
            {
                "filing_type_code": "TRANS",
                "corp_type_code": "BEN",
                "fee_code": "EN107",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": None,
                "priority_fee_code": None,
                "service_fee_code": None,
            },
            {
                "filing_type_code": "ALTER",
                "corp_type_code": "ULC",
                "fee_code": "EN113",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None,
                "future_effective_fee_code": "FUT01",
                "priority_fee_code": "PRI01",
                "service_fee_code": "TRF01",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "delete from fee_schedule where filing_type_code='TRANS' and corp_type_code in ('BC', 'BEN')"
    )
    op.execute(
        "delete from fee_schedule where filing_type_code='ALTER' and corp_type_code='ULC'"
    )
    op.execute("delete from filing_type where code='TRANS'")
    op.execute("delete from fee_code where code='EN113'")
    op.execute("delete from corp_type where code='ULC'")
    # ### end Alembic commands ###
