"""empty message

Revision ID: bcb296e7f6f4
Revises: 444df7ad2d80
Create Date: 2020-08-18 16:21:20.171817

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "bcb296e7f6f4"
down_revision = "444df7ad2d80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoice",
        "updated_name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "payment",
        "updated_name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_transaction",
        "pay_response_url",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_transaction",
        "pay_system_url",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=2000),
        existing_nullable=True,
    )
    op.alter_column("statement", "to_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column(
        "statement_settings", "to_date", existing_type=sa.DATE(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "statement_settings", "to_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column("statement", "to_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column(
        "payment_transaction",
        "pay_system_url",
        existing_type=sa.String(length=2000),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "payment_transaction",
        "pay_response_url",
        existing_type=sa.String(length=2000),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "payment",
        "updated_name",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "invoice",
        "updated_name",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
