"""Add in GL error to refunds, 
   that way we can record the error message and use 
   this as a mechanism to filter out.

Revision ID: bf3f354aa6ad
Revises: 320dcaf6cc37
Create Date: 2022-09-04 06:55:10.254146

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bf3f354aa6ad"
down_revision = "320dcaf6cc37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refunds", sa.Column("gl_error", sa.String(length=250), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refunds", "gl_error")
    # ### end Alembic commands ###
