"""add new column-total_usd for routing slip creation

Revision ID: d73cbcdd2f25
Revises: ff2d7fe31ec9
Create Date: 2022-01-27 15:01:59.324503

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d73cbcdd2f25"
down_revision = "ff2d7fe31ec9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column(
            "paid_usd_amount",
            sa.Numeric(),
            nullable=True,
            comment="Amount PAID as part " "of payment in USD",
        ),
    )
    op.add_column("routing_slips", sa.Column("total_usd", sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routing_slips", "total_usd")
    op.drop_column("payments", "paid_usd_amount")
    # ### end Alembic commands ###
