"""adding_routing_slip_comments

Revision ID: db40bb37a30c
Revises: 999f11310f30
Create Date: 2021-10-23 00:03:45.881835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db40bb37a30c'
down_revision = '999f11310f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.String(length=4096), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('routing_slip_number', sa.String(), nullable=True),
    sa.Column('submitter_display_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['routing_slip_number'], ['routing_slips.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_routing_slip_number'), 'comments', ['routing_slip_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_routing_slip_number'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
