"""Add in audit columns for distribution_code_links and fee_schedules. 

Revision ID: e06565b323db
Revises: 59fc9d74101f
Create Date: 2022-07-16 09:07:52.280277

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = 'e06565b323db'
down_revision = '59fc9d74101f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_code_links', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('distribution_code_links', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('distribution_code_links', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.add_column('distribution_code_links', sa.Column('created_name', sa.String(length=100), nullable=True))
    op.add_column('distribution_code_links', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('distribution_code_links', sa.Column('updated_name', sa.String(length=50), nullable=True))
    op.add_column('fee_schedules', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('fee_schedules', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('fee_schedules', sa.Column('created_by', sa.String(length=50), nullable=True, default=-1))
    op.add_column('fee_schedules', sa.Column('created_name', sa.String(length=100), nullable=True))
    op.add_column('fee_schedules', sa.Column('updated_by', sa.String(length=50), nullable=True))
    op.add_column('fee_schedules', sa.Column('updated_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_schedules', 'updated_name')
    op.drop_column('fee_schedules', 'updated_by')
    op.drop_column('fee_schedules', 'created_name')
    op.drop_column('fee_schedules', 'created_by')
    op.drop_column('fee_schedules', 'updated_on')
    op.drop_column('fee_schedules', 'created_on')
    op.drop_column('distribution_code_links', 'updated_name')
    op.drop_column('distribution_code_links', 'updated_by')
    op.drop_column('distribution_code_links', 'created_name')
    op.drop_column('distribution_code_links', 'created_by')
    op.drop_column('distribution_code_links', 'updated_on')
    op.drop_column('distribution_code_links', 'created_on')
    # ### end Alembic commands ###
