"""nsf_fee_code

Revision ID: e699674b1774
Revises: b05d371ad030
Create Date: 2020-11-27 10:28:35.417779

"""
from datetime import datetime, timezone

from alembic import op
from sqlalchemy import Date, Float, String
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = 'e699674b1774'
down_revision = 'b05d371ad030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    corp_type_table = table('corp_type',
                            column('code', String),
                            column('description', String)
                            )
    fee_code_table = table('fee_code',
                           column('code', String),
                           column('amount', Float)
                           )
    filing_type_table = table('filing_type',
                              column('code', String),
                              column('description', String)
                              )

    fee_schedule_table = table(
        "fee_schedule",
        column("filing_type_code", String),
        column("corp_type_code", String),
        column("fee_code", String),
        column("fee_start_date", Date),
        column("fee_end_date", Date)
    )

    # Product code/corp type
    op.bulk_insert(
        corp_type_table,
        [
            {'code': 'BCR', 'description': 'BC Registries'}
        ]
    )

    # Fee code, starting with EN201 as its a new product

    op.bulk_insert(
        fee_code_table,
        [
            {'code': 'NSF01', 'amount': 30}
        ]
    )

    # Filing Types
    op.bulk_insert(
        filing_type_table,
        [
            {'code': 'NSF', 'description': 'NSF'}
        ]
    )
    # Fee Schedules
    op.bulk_insert(
        fee_schedule_table,
        [
            {
                "filing_type_code": "NSF",
                "corp_type_code": "BCR",
                "fee_code": "NSF01",
                "fee_start_date": datetime.now(tz=timezone.utc),
                "fee_end_date": None
            }
        ]
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("delete from fee_schedule where filing_type_code in ('NSF') ")
    op.execute("delete from filing_type where code in ('NSF') ")
    op.execute("delete from fee_code where code in ('NSF01') ")
    op.execute("delete from corp_type where code in ('BCR') ")
    # ### end Alembic commands ###
