"""fas_audit_fields

Revision ID: e7fb85dbffae
Revises: 2c1ecdec185a
Create Date: 2022-01-11 11:51:04.067629

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e7fb85dbffae"
down_revision = "2c1ecdec185a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_fees_version",
        sa.Column("created_on", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_on", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "apply_filing_fees", sa.Boolean(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "service_fee_code", sa.String(length=10), autoincrement=False, nullable=True
        ),
        sa.Column("product", sa.String(length=20), autoincrement=False, nullable=True),
        sa.Column(
            "created_by", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_name", sa.String(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_by", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_name", sa.String(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_account_fees_version_account_id"),
        "account_fees_version",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_fees_version_end_transaction_id"),
        "account_fees_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_fees_version_operation_type"),
        "account_fees_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_fees_version_transaction_id"),
        "account_fees_version",
        ["transaction_id"],
        unique=False,
    )
    op.add_column("account_fees", sa.Column("created_on", sa.DateTime(), nullable=True))
    op.add_column("account_fees", sa.Column("updated_on", sa.DateTime(), nullable=True))
    op.add_column(
        "account_fees", sa.Column("created_by", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "account_fees", sa.Column("created_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "account_fees", sa.Column("updated_by", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "account_fees", sa.Column("updated_name", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "refunds", sa.Column("decision_made_by", sa.String(length=50), nullable=True)
    )
    op.add_column("refunds", sa.Column("decision_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refunds", "decision_date")
    op.drop_column("refunds", "decision_made_by")
    op.drop_column("account_fees", "updated_name")
    op.drop_column("account_fees", "updated_by")
    op.drop_column("account_fees", "created_name")
    op.drop_column("account_fees", "created_by")
    op.drop_column("account_fees", "updated_on")
    op.drop_column("account_fees", "created_on")
    op.drop_index(
        op.f("ix_account_fees_version_transaction_id"),
        table_name="account_fees_version",
    )
    op.drop_index(
        op.f("ix_account_fees_version_operation_type"),
        table_name="account_fees_version",
    )
    op.drop_index(
        op.f("ix_account_fees_version_end_transaction_id"),
        table_name="account_fees_version",
    )
    op.drop_index(
        op.f("ix_account_fees_version_account_id"), table_name="account_fees_version"
    )
    op.drop_table("account_fees_version")
    # ### end Alembic commands ###
