"""changes_for_cg_ejv

Revision ID: ebee125e6877
Revises: 6f0fe9f23d8c
Create Date: 2021-02-05 13:01:25.197166

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ebee125e6877"
down_revision = "6f0fe9f23d8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ejv_headers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("disbursement_status_code", sa.String(length=20), nullable=True),
        sa.Column("ejv_file_id", sa.Integer(), nullable=False),
        sa.Column("partner_code", sa.String(length=10), nullable=True),
        sa.Column("payment_account_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["disbursement_status_code"],
            ["disbursement_status_codes.code"],
        ),
        sa.ForeignKeyConstraint(
            ["ejv_file_id"],
            ["ejv_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["partner_code"],
            ["corp_types.code"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_account_id"],
            ["payment_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "corp_types", sa.Column("batch_type", sa.String(length=2), nullable=True)
    )
    op.add_column(
        "ejv_files",
        sa.Column("disbursement_status_code", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "ejv_files", sa.Column("feedback_file_ref", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        "ejv_files_disbursement_status_code_fk",
        "ejv_files",
        "disbursement_status_codes",
        ["disbursement_status_code"],
        ["code"],
    )
    op.add_column(
        "ejv_invoice_links", sa.Column("ejv_header_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "ejv_invoice_links_ejv_file_id_fkey", "ejv_invoice_links", type_="foreignkey"
    )
    op.create_foreign_key(
        "ejv_invoice_links_ejv_header_id_fk",
        "ejv_invoice_links",
        "ejv_headers",
        ["ejv_header_id"],
        ["id"],
    )
    op.drop_column("ejv_invoice_links", "ejv_file_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ejv_invoice_links",
        sa.Column("ejv_file_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        "ejv_invoice_links_ejv_header_id_fk", "ejv_invoice_links", type_="foreignkey"
    )
    op.create_foreign_key(
        "ejv_invoice_links_ejv_file_id_fkey",
        "ejv_invoice_links",
        "ejv_files",
        ["ejv_file_id"],
        ["id"],
    )
    op.drop_column("ejv_invoice_links", "ejv_header_id")
    op.drop_constraint(
        "ejv_files_disbursement_status_code_fk", "ejv_files", type_="foreignkey"
    )
    op.drop_column("ejv_files", "feedback_file_ref")
    op.drop_column("ejv_files", "disbursement_status_code")
    op.drop_column("corp_types", "batch_type")

    op.drop_table("ejv_headers")
    # ### end Alembic commands ###
