"""name_req_description_changes

Revision ID: f1ed292af77f
Revises: 41f76e6c82eb
Create Date: 2021-01-13 12:02:13.958771

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "f1ed292af77f"
down_revision = "41f76e6c82eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "update filing_type set description='Name Request fee' where code='NM620'"
    )
    op.execute(
        "update filing_type set description='Priority Request fee' where code='NM606'"
    )
    op.execute(
        "update payment_line_item set description='Name Request fee' where fee_schedule_id = (select fee_schedule_id from fee_schedule where filing_type_code='NM620')"
    )
    op.execute(
        "update payment_line_item set description='Priority Request fee' where fee_schedule_id = (select fee_schedule_id from fee_schedule where filing_type_code='NM606')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "update filing_type set description='Reg. Submission Online' where code='NM620'"
    )
    op.execute(
        "update filing_type set description='Upgrade to Priority' where code='NM606'"
    )
    op.execute(
        "update payment_line_item set description='Reg. Submission Online' where fee_schedule_id = (select fee_schedule_id from fee_schedule where filing_type_code='NM620')"
    )
    op.execute(
        "update payment_line_item set description='Upgrade to Priority' where fee_schedule_id = (select fee_schedule_id from fee_schedule where filing_type_code='NM606')"
    )
    # ### end Alembic commands ###
