"""Add correction status

Revision ID: f497d603602e
Revises: 5418ad1a5fdd
Create Date: 2022-12-09 10:34:53.630824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f497d603602e'
down_revision = '5418ad1a5fdd'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("insert into routing_slip_status_codes (code, description) values ('CORRECTION','Correction')")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from routing_slip_status_codes where code = \'CORRECTION\';')
    # ### end Alembic commands ###
