"""Add correction status

Revision ID: f497d603602e
Revises: 5418ad1a5fdd
Create Date: 2022-12-09 10:34:53.630824

"""

from alembic import op
from sqlalchemy import String
from sqlalchemy.sql import column, table


# revision identifiers, used by Alembic.
revision = "f497d603602e"
down_revision = "5418ad1a5fdd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "insert into routing_slip_status_codes (code, description) values ('CORRECTION','Correction')"
    )
    error_code_table = table(
        "error_codes",
        column("code", String),
        column("title", String),
        column("detail", String),
    )
    op.bulk_insert(
        error_code_table,
        [
            {
                "code": "RS_HAS_TRANSACTIONS",
                "title": "Unable to Void Routing Slip",
                "detail": "A routing slip with transactions cannot change status to void.",
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("delete from routing_slip_status_codes where code = 'CORRECTION';")
    op.execute("delete from error_codes where code in ('RS_HAS_TRANSACTIONS')")
    # ### end Alembic commands ###
