"""ap_changes

Revision ID: f8408a4a782c
Revises: 0d885750ded9
Create Date: 2021-12-16 16:24:33.219729

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import column, table

# revision identifiers, used by Alembic.
revision = "f8408a4a782c"
down_revision = "0d885750ded9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ejv_files", sa.Column("file_type", sa.String(), nullable=True))
    op.drop_column("ejv_files", "is_distribution")

    op.execute("delete from routing_slip_status_codes where code in ('WRITE_OFF');")
    rs_status_table = table(
        "routing_slip_status_codes",
        column("code", sa.String),
        column("description", sa.String),
    )
    op.bulk_insert(
        rs_status_table,
        [
            {"code": "WRITE_OFF_REQUESTED", "description": "Write Off Requested"},
            {"code": "WRITE_OFF_AUTHORIZED", "description": "Write Off Authorized"},
            {"code": "WRITE_OFF_COMPLETED", "description": "Write Off Completed"},
            {"code": "REFUND_UPLOADED", "description": "Refund Uploaded"},
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ejv_files",
        sa.Column("is_distribution", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("ejv_files", "file_type")
    op.execute(
        "delete from routing_slip_status_codes where code in "
        "('WRITE_OFF_REQUESTED', 'WRITE_OFF_AUTHORIZED', 'WRITE_OFF_COMPLETED', 'REFUND_UPLOADED');"
    )
    # ### end Alembic commands ###
