"""name_length_gl_codes

Revision ID: ff2d7fe31ec9
Revises: e7fb85dbffae
Create Date: 2022-01-21 15:05:19.298887

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ff2d7fe31ec9"
down_revision = "e7fb85dbffae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "distribution_codes",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=250),
        existing_nullable=True,
    )
    op.alter_column(
        "distribution_codes_version",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=250),
        existing_nullable=True,
        autoincrement=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "distribution_codes_version",
        "name",
        existing_type=sa.String(length=250),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
        autoincrement=False,
    )
    op.alter_column(
        "distribution_codes",
        "name",
        existing_type=sa.String(length=250),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
