name: Draft release

on:
  push:
    branches:
      - main

jobs:
  draft-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=release-name::Payment Services $(date +'%B, %Y') Release"
      - uses: release-drafter/release-drafter@v5
        with:
          name: "${{ steps.date.outputs.release-name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
