name: FTP Poller CD

on:
  push:
    branches:
      - development
      - master
    paths:
      - "jobs/ftp-poller/**"
  workflow_dispatch:
    inputs:
      environement:
        description: "Environment (dev/test)"
        required: true
        default: "dev"

jobs:
  ftp-poller-cd:
    runs-on: ubuntu-latest
    if: github.repository == 'bcgov/sbc-pay'
    steps:
      - uses: actions/checkout@v2
      - name: Set env by input
        run: |
          echo "TAG_NAME=${{ github.event.inputs.environement }}" >> $GITHUB_ENV

      - name: Set env by master branch
        if: env.TAG_NAME == '' && github.ref == 'refs/heads/master'
        run: |
          echo "TAG_NAME=test" >> $GITHUB_ENV

      - name: Set env by development branch
        if: env.TAG_NAME == '' && github.ref == 'refs/heads/development'
        run: |
          echo "TAG_NAME=dev" >> $GITHUB_ENV

      - uses: pwei1018/bcrs-cd-action@latest
        with:
          WORKING_DIRECTORY: "./jobs/ftp-poller"
          APP_NAME: "ftp-poller"
          VAULTS: '[{ \"vault\": \"shared\", \"application\": [\"minio\", \"nats\"]}, {\"vault\": \"relationship\",\"application\": [\"postgres-pay\", \"pay-api\", \"sentry\", \"jwt\", \"ftp-poller\",\"payment-reconciliations\"]}]'
          SKIP_OP: "false"
          OP_PARAMETERS: ${{ secrets.OP_PARAMETERS }}
          OPENSHIFT_LOGIN_REGISTRY: ${{ secrets.OPENSHIFT_LOGIN_REGISTRY }}
          OPENSHIFT_DOCKER_REGISTRY: ${{ secrets.OPENSHIFT_DOCKER_REGISTRY }}
          OPENSHIFT_SA_NAME: ${{ secrets.OPENSHIFT_SA_NAME }}
          OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT_SA_TOKEN }}
          OPENSHIFT_REPOSITORY: ${{ secrets.OPENSHIFT_REPOSITORY }}
          OPENSHIFT_REPOSITORY_DEPLOYMENT: ${{ secrets.OPENSHIFT_REPOSITORY }}

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "*FTP Poller Built and Deployed to ${{env.TAG_NAME}}*"
          channel: "#registries-bot"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
